import type { Exercise } from "./types";

// Curated, beginner-first exercise library. Every entry carries a plain-English
// howTo so a newcomer can execute it without prior knowledge. Equipment tiers
// list where an exercise is available; the generator intersects them with what
// the user says they have (see generator.ts -> allowedTiers).

export const EXERCISES: Exercise[] = [
  // ============================== WARMUPS ==============================
  {
    id: "march-in-place", name: "March in Place", emoji: "🚶", type: "warmup",
    focus: ["full", "legs", "arms", "core", "cardio"], muscles: ["cardio", "mobility"],
    muscleLabel: "Full Body · Heart Rate", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "60 seconds", defaultRest: 0, defaultDuration: 60,
    tip: "Lift knees to hip height, pump your arms. Get the blood moving.",
    howTo: {
      setup: "Stand tall in a clear space, feet hip-width apart, arms bent at 90°.",
      steps: ["Drive one knee up toward hip height.", "Lower it and drive the other knee up.", "Swing opposite arm with each knee, building a steady rhythm."],
      mistakes: ["Hunching forward — stay tall.", "Going too fast too soon — this is a warmup."],
      easier: "Keep knees low and slow.", harder: "Lift knees higher and quicken the pace.",
    },
  },
  {
    id: "arm-circles", name: "Arm Circles", emoji: "🔄", type: "warmup",
    focus: ["full", "arms", "core"], muscles: ["shoulders", "mobility"],
    muscleLabel: "Shoulders · Mobility", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Big slow circles forward, then backward. Loosen the shoulders.",
    howTo: {
      setup: "Stand with feet shoulder-width, arms extended straight out to the sides.",
      steps: ["Draw small circles forward, gradually widening them.", "After 15s, reverse direction and circle backward."],
      mistakes: ["Shrugging shoulders up to ears — keep them down.", "Bending the elbows."],
      easier: "Smaller circles.", harder: "Larger, slower circles for more range.",
    },
  },
  {
    id: "bodyweight-squat-warm", name: "Bodyweight Squats", emoji: "🦵", type: "warmup",
    focus: ["full", "legs", "core"], muscles: ["quads", "glutes", "mobility"],
    muscleLabel: "Legs · Mobility", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "40 seconds", defaultRest: 0, defaultDuration: 40,
    tip: "Feet shoulder-width, chest up, sit back into your heels.",
    howTo: {
      setup: "Feet shoulder-width apart, toes slightly out, arms reaching forward for balance.",
      steps: ["Push hips back as if sitting into a chair.", "Lower until thighs are roughly parallel to the floor.", "Drive through your heels to stand tall."],
      mistakes: ["Knees caving inward.", "Lifting heels off the floor."],
      easier: "Squat to a chair and tap it.", harder: "Slow the lowering to 3 seconds.",
    },
  },
  {
    id: "leg-swings", name: "Leg Swings", emoji: "🦿", type: "warmup",
    focus: ["legs", "full", "cardio"], muscles: ["hamstrings", "glutes", "mobility"],
    muscleLabel: "Hips · Hamstrings", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Hold a wall, swing one leg front-to-back like a pendulum.",
    howTo: {
      setup: "Stand beside a wall for support, weight on one leg.",
      steps: ["Swing the free leg forward and back in a controlled arc.", "Keep your torso upright.", "Switch legs halfway through."],
      mistakes: ["Swinging so hard you lose balance.", "Rounding the back."],
      easier: "Smaller swings.", harder: "Add a gentle side-to-side swing too.",
    },
    excludedBy: [],
  },
  {
    id: "jumping-jacks", name: "Jumping Jacks", emoji: "⭐", type: "warmup",
    focus: ["full", "cardio", "legs"], muscles: ["cardio", "fullbody"],
    muscleLabel: "Full Body · Heart Rate", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Jump feet wide while raising arms overhead, then back. Stay light.",
    howTo: {
      setup: "Stand tall, feet together, arms at your sides.",
      steps: ["Jump feet out wide while sweeping arms overhead.", "Jump back to start, arms down.", "Keep a steady bouncing rhythm."],
      mistakes: ["Landing flat and heavy — land soft on the balls of your feet."],
      easier: "Step out one foot at a time (no jump).", harder: "Quicken the pace.",
    },
    excludedBy: ["no-jumping", "quiet"],
  },
  {
    id: "cat-cow", name: "Cat-Cow", emoji: "🐈", type: "warmup",
    focus: ["core", "full"], muscles: ["core", "back", "mobility"],
    muscleLabel: "Spine · Core Mobility", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "On all fours, alternate arching and rounding your back slowly.",
    howTo: {
      setup: "On hands and knees, wrists under shoulders, knees under hips.",
      steps: ["Drop your belly and lift your gaze (cow).", "Round your spine toward the ceiling and tuck your chin (cat).", "Flow slowly with your breath."],
      mistakes: ["Rushing — move with control.", "Forcing the range."],
      easier: "Smaller movements.", harder: "Pause and breathe at each end.",
    },
    excludedBy: ["no-floor"],
  },

  // ============================== LEGS ==============================
  {
    id: "goblet-squat", name: "Goblet Squat", emoji: "🏋️", type: "strength",
    focus: ["legs", "full"], muscles: ["quads", "glutes", "core"],
    muscleLabel: "Quads · Glutes · Core", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 45,
    tip: "Hold a dumbbell at your chest. Squat deep, keep your chest tall.",
    howTo: {
      setup: "Hold one dumbbell vertically against your chest with both hands, feet shoulder-width.",
      steps: ["Push your hips back and bend your knees.", "Lower until thighs are parallel, elbows tracking inside knees.", "Drive through your heels to stand."],
      mistakes: ["Letting the chest collapse forward.", "Knees caving in."],
      easier: "Use a lighter weight or bodyweight only.", harder: "Pause 2s at the bottom.",
    },
    excludedBy: ["knee-friendly"],
  },
  {
    id: "reverse-lunge", name: "Reverse Lunge", emoji: "🚶‍♂️", type: "strength",
    focus: ["legs", "full"], muscles: ["quads", "glutes", "hamstrings"],
    muscleLabel: "Quads · Glutes", equipment: ["bodyweight", "dumbbell"], loaded: false,
    defaultSets: 3, defaultReps: "10 each side", defaultRest: 45,
    tip: "Step back, drop the back knee toward the floor, then drive up.",
    howTo: {
      setup: "Stand tall, hands on hips (or a dumbbell in each hand).",
      steps: ["Step one foot back and lower until both knees are ~90°.", "Keep your front shin vertical.", "Push through the front heel to return; alternate legs."],
      mistakes: ["Front knee shooting past the toes.", "Leaning the torso forward."],
      easier: "Hold a wall for balance.", harder: "Add dumbbells.",
    },
  },
  {
    id: "glute-bridge", name: "Glute Bridge", emoji: "🌉", type: "strength",
    focus: ["legs", "core", "full"], muscles: ["glutes", "hamstrings", "core"],
    muscleLabel: "Glutes · Hamstrings", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "15 reps", defaultRest: 30,
    tip: "Lie on your back, drive your hips up, squeeze your glutes at the top.",
    howTo: {
      setup: "Lie on your back, knees bent, feet flat and hip-width, arms by your sides.",
      steps: ["Press through your heels and lift your hips toward the ceiling.", "Squeeze your glutes hard at the top.", "Lower with control."],
      mistakes: ["Over-arching the lower back — squeeze glutes, not back.", "Pushing through the toes."],
      easier: "Smaller lift.", harder: "Pause 2s at the top or do single-leg.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "rdl-dumbbell", name: "Dumbbell Romanian Deadlift", emoji: "🏋️‍♀️", type: "strength",
    focus: ["legs", "full"], muscles: ["hamstrings", "glutes", "back"],
    muscleLabel: "Hamstrings · Glutes", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 45,
    tip: "Hinge at the hips, dumbbells sliding down your thighs, flat back.",
    howTo: {
      setup: "Hold a dumbbell in each hand in front of your thighs, feet hip-width, knees soft.",
      steps: ["Push your hips back, lowering the weights along your legs.", "Stop when you feel a stretch in your hamstrings (about shin level).", "Drive hips forward to stand tall."],
      mistakes: ["Rounding the back — keep it flat.", "Turning it into a squat."],
      easier: "Lighter weight, smaller range.", harder: "Slow the lowering to 3s.",
    },
  },
  {
    id: "calf-raise", name: "Calf Raise", emoji: "🦶", type: "strength",
    focus: ["legs"], muscles: ["calves"],
    muscleLabel: "Calves", equipment: ["bodyweight", "dumbbell"], loaded: false,
    defaultSets: 3, defaultReps: "15 reps", defaultRest: 30,
    tip: "Rise onto the balls of your feet, pause, lower slowly.",
    howTo: {
      setup: "Stand tall near a wall for balance, feet hip-width.",
      steps: ["Push through the balls of your feet and lift your heels high.", "Pause at the top.", "Lower slowly until heels nearly touch the floor."],
      mistakes: ["Bouncing through reps.", "Rolling onto the outside of the foot."],
      easier: "Hold the wall.", harder: "Hold dumbbells or do one leg at a time.",
    },
  },
  {
    id: "wall-sit", name: "Wall Sit", emoji: "🧱", type: "strength",
    focus: ["legs", "core"], muscles: ["quads", "glutes"],
    muscleLabel: "Quads · Endurance", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "30 seconds", defaultRest: 30, defaultDuration: 30,
    tip: "Back against the wall, slide down to a 90° sit, hold.",
    howTo: {
      setup: "Stand with your back flat against a wall, feet about two feet out.",
      steps: ["Slide down until your thighs are parallel to the floor.", "Knees stacked over ankles at 90°.", "Hold, breathing steadily."],
      mistakes: ["Knees past the toes.", "Putting hands on the thighs for help."],
      easier: "Don't sit as low.", harder: "Lower deeper or extend the hold.",
    },
    excludedBy: ["knee-friendly"],
  },
  {
    id: "banded-squat", name: "Banded Squat", emoji: "🔵", type: "strength",
    focus: ["legs", "full"], muscles: ["quads", "glutes"],
    muscleLabel: "Quads · Glutes", equipment: ["bands"], loaded: false,
    defaultSets: 3, defaultReps: "15 reps", defaultRest: 30,
    tip: "Loop a band above your knees and squat, pushing knees out against it.",
    howTo: {
      setup: "Place a loop band just above your knees, feet shoulder-width.",
      steps: ["Push your knees out against the band.", "Sit back into a squat, keeping tension on the band.", "Drive up through your heels."],
      mistakes: ["Letting the band pull your knees inward.", "Shallow depth."],
      easier: "Lighter band.", harder: "Pause at the bottom.",
    },
  },
  {
    id: "step-up", name: "Step-Up", emoji: "🪜", type: "strength",
    focus: ["legs", "full", "cardio"], muscles: ["quads", "glutes"],
    muscleLabel: "Quads · Glutes", equipment: ["bodyweight", "dumbbell"], loaded: false,
    defaultSets: 3, defaultReps: "10 each side", defaultRest: 40,
    tip: "Step onto a sturdy bench/box, drive through the top leg.",
    howTo: {
      setup: "Stand facing a knee-height sturdy bench or step.",
      steps: ["Place one whole foot on the step.", "Drive through that heel to stand up on top.", "Step back down with control; alternate legs."],
      mistakes: ["Pushing off the bottom foot instead of the top leg.", "Using an unstable surface."],
      easier: "Use a lower step.", harder: "Hold dumbbells.",
    },
    excludedBy: ["knee-friendly"],
  },

  // ============================== ARMS / UPPER ==============================
  {
    id: "db-curl", name: "Dumbbell Biceps Curl", emoji: "💪", type: "strength",
    focus: ["arms", "full"], muscles: ["biceps"],
    muscleLabel: "Biceps", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 30,
    tip: "Elbows pinned to your sides, curl up, lower slowly.",
    howTo: {
      setup: "Stand tall, a dumbbell in each hand, palms facing forward.",
      steps: ["Keeping elbows glued to your sides, curl the weights up.", "Squeeze your biceps at the top.", "Lower slowly to full extension."],
      mistakes: ["Swinging the body to lift.", "Elbows drifting forward."],
      easier: "Lighter weight or one arm at a time.", harder: "3s lowering tempo.",
    },
  },
  {
    id: "hammer-curl", name: "Hammer Curl", emoji: "🔨", type: "strength",
    focus: ["arms", "full"], muscles: ["biceps"],
    muscleLabel: "Biceps · Forearms", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 30,
    tip: "Same as a curl but palms face each other the whole time.",
    howTo: {
      setup: "Dumbbell in each hand, palms facing your body (thumbs up).",
      steps: ["Curl the weights up keeping palms facing inward.", "Squeeze at the top.", "Lower with control."],
      mistakes: ["Rotating the wrists.", "Using momentum."],
      easier: "Lighter weight.", harder: "Alternate slow single arms.",
    },
  },
  {
    id: "triceps-kickback", name: "Triceps Kickback", emoji: "🦵", type: "strength",
    focus: ["arms"], muscles: ["triceps"],
    muscleLabel: "Triceps", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 30,
    tip: "Hinge forward, upper arm still, extend the weight straight back.",
    howTo: {
      setup: "Hinge at the hips ~45°, a dumbbell in each hand, upper arms tucked to your sides.",
      steps: ["Keeping upper arms still, straighten your elbows to press the weights back.", "Squeeze your triceps.", "Return to 90° with control."],
      mistakes: ["Moving the upper arm.", "Rounding the back."],
      easier: "Lighter weight, one arm.", harder: "Pause at full extension.",
    },
  },
  {
    id: "overhead-press", name: "Dumbbell Shoulder Press", emoji: "⬆️", type: "strength",
    focus: ["arms", "full"], muscles: ["shoulders", "triceps"],
    muscleLabel: "Shoulders · Triceps", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "10 reps", defaultRest: 45,
    tip: "Start at ear level, press overhead without arching your back.",
    howTo: {
      setup: "Sit or stand tall, dumbbells at ear height, palms forward.",
      steps: ["Brace your core.", "Press the dumbbells straight overhead until arms are extended.", "Lower back to ear level with control."],
      mistakes: ["Arching the lower back.", "Flaring elbows too far back."],
      easier: "Lighter weight or one arm.", harder: "Slow the lowering.",
    },
    excludedBy: ["shoulder-friendly"],
  },
  {
    id: "lateral-raise", name: "Lateral Raise", emoji: "🦅", type: "strength",
    focus: ["arms"], muscles: ["shoulders"],
    muscleLabel: "Shoulders", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 30,
    tip: "Raise the dumbbells out to the sides to shoulder height, soft elbows.",
    howTo: {
      setup: "Stand tall, a light dumbbell in each hand at your sides, slight elbow bend.",
      steps: ["Lift the weights out to the sides until arms are parallel to the floor.", "Lead with your elbows, pinkies slightly up.", "Lower slowly."],
      mistakes: ["Going too heavy and shrugging.", "Raising above shoulder height."],
      easier: "Very light weight.", harder: "Pause at the top.",
    },
    excludedBy: ["shoulder-friendly"],
  },
  {
    id: "pushup", name: "Push-Up", emoji: "🫷", type: "strength",
    focus: ["arms", "full", "core"], muscles: ["chest", "triceps", "shoulders", "core"],
    muscleLabel: "Chest · Triceps · Core", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "10 reps", defaultRest: 40,
    tip: "Body straight as a plank, lower your chest, press back up.",
    howTo: {
      setup: "Hands slightly wider than shoulders, body in a straight line from head to heels.",
      steps: ["Bend your elbows to lower your chest toward the floor.", "Keep elbows at ~45° from your body.", "Press back up to full arm extension."],
      mistakes: ["Hips sagging or piking up.", "Flaring elbows straight out."],
      easier: "Drop to your knees or push up from a wall/bench.", harder: "Slow 3s lowering.",
    },
  },
  {
    id: "chair-dip", name: "Chair Triceps Dip", emoji: "🪑", type: "strength",
    focus: ["arms"], muscles: ["triceps", "shoulders"],
    muscleLabel: "Triceps · Shoulders", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "10 reps", defaultRest: 40,
    tip: "Hands on a sturdy chair edge, bend elbows to dip, press up.",
    howTo: {
      setup: "Sit on the edge of a sturdy chair, hands gripping the edge beside your hips, feet out front.",
      steps: ["Slide your hips off the edge.", "Bend your elbows straight back to lower your hips.", "Press through your palms to rise."],
      mistakes: ["Elbows flaring out.", "Shrugging shoulders to the ears."],
      easier: "Bend knees closer to you.", harder: "Walk feet further out / straighten legs.",
    },
    excludedBy: ["shoulder-friendly"],
  },
  {
    id: "band-pull-apart", name: "Band Pull-Apart", emoji: "🎗️", type: "strength",
    focus: ["arms", "full"], muscles: ["back", "shoulders"],
    muscleLabel: "Upper Back · Rear Delts", equipment: ["bands"], loaded: false,
    defaultSets: 3, defaultReps: "15 reps", defaultRest: 30,
    tip: "Hold a band at shoulder height, pull it apart, squeeze shoulder blades.",
    howTo: {
      setup: "Hold a resistance band with both hands at shoulder height, arms extended forward.",
      steps: ["Pull the band apart by squeezing your shoulder blades together.", "Bring the band toward your chest.", "Return slowly with control."],
      mistakes: ["Shrugging the shoulders.", "Bending the elbows."],
      easier: "Wider grip (less tension).", harder: "Narrow grip or stronger band.",
    },
  },

  // ============================== BACK (full-body) ==============================
  {
    id: "db-row", name: "Dumbbell Row", emoji: "🚣", type: "strength",
    focus: ["full", "arms"], muscles: ["back", "biceps"],
    muscleLabel: "Back · Biceps", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "10 each side", defaultRest: 40,
    tip: "Hinge forward, pull the dumbbell to your hip, squeeze your back.",
    howTo: {
      setup: "Place one knee and hand on a bench, other foot on floor, dumbbell hanging from the free hand.",
      steps: ["Pull the dumbbell up toward your hip, leading with your elbow.", "Squeeze your shoulder blade at the top.", "Lower slowly; switch sides."],
      mistakes: ["Rotating the torso to yank the weight.", "Pulling to the chest instead of the hip."],
      easier: "Lighter weight.", harder: "Pause at the top for 1s.",
    },
  },
  {
    id: "band-row", name: "Resistance Band Row", emoji: "🔗", type: "strength",
    focus: ["full", "arms"], muscles: ["back", "biceps", "core"],
    muscleLabel: "Back · Biceps · Core", equipment: ["bands"], loaded: false,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 30,
    tip: "Anchor a band at chest height, sit tall, pull to your belly button.",
    howTo: {
      setup: "Anchor a band at chest height (or loop around your feet while seated), holding an end in each hand.",
      steps: ["Sit or stand tall with arms extended.", "Pull the handles to your belly button, elbows close to your sides.", "Squeeze your back, then return slowly."],
      mistakes: ["Leaning back to pull.", "Letting the shoulders shrug up."],
      easier: "Step closer to the anchor.", harder: "Step back for more tension.",
    },
  },
  {
    id: "db-chest-press", name: "Dumbbell Chest Press", emoji: "🛏️", type: "strength",
    focus: ["full", "arms"], muscles: ["chest", "triceps", "shoulders"],
    muscleLabel: "Chest · Triceps", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 45,
    tip: "On a bench or floor, dumbbells at chest level, press up and together.",
    howTo: {
      setup: "Lie on a bench (or the floor) holding a dumbbell in each hand at chest level, elbows at ~45°.",
      steps: ["Press the dumbbells up until your arms are extended.", "Bring them slightly together at the top.", "Lower with control to chest level."],
      mistakes: ["Flaring elbows straight out to 90°.", "Bouncing the weights."],
      easier: "Lighter weight, floor press (shorter range).", harder: "Slow 3s lowering.",
    },
  },
  {
    id: "reverse-fly", name: "Reverse Fly", emoji: "🦋", type: "strength",
    focus: ["full", "arms"], muscles: ["back", "shoulders"],
    muscleLabel: "Upper Back · Rear Delts", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 30,
    tip: "Hinge forward, raise light dumbbells out to the sides like wings.",
    howTo: {
      setup: "Hinge forward ~45° with a flat back, light dumbbells hanging beneath you, palms facing each other.",
      steps: ["Raise the weights out to the sides, squeezing your shoulder blades.", "Stop at shoulder height.", "Lower slowly."],
      mistakes: ["Using momentum.", "Rounding the back."],
      easier: "Very light weight.", harder: "Pause at the top.",
    },
  },

  // ============================== CORE ==============================
  {
    id: "plank", name: "Plank Hold", emoji: "🧱", type: "strength",
    focus: ["core", "full"], muscles: ["core", "shoulders"],
    muscleLabel: "Core · Shoulders", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "30 seconds", defaultRest: 30, defaultDuration: 30,
    tip: "Forearms down, body straight as a board. Breathe steadily.",
    howTo: {
      setup: "Forearms on the floor under your shoulders, legs extended behind you on your toes.",
      steps: ["Lift your hips so your body forms a straight line.", "Brace your abs and squeeze your glutes.", "Hold, breathing steadily."],
      mistakes: ["Hips sagging or piking up.", "Holding your breath."],
      easier: "Drop to your knees.", harder: "Extend the hold or lift one foot.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "dead-bug", name: "Dead Bug", emoji: "🐛", type: "strength",
    focus: ["core"], muscles: ["core"],
    muscleLabel: "Deep Core", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "10 each side", defaultRest: 30,
    tip: "On your back, lower opposite arm and leg, keep your low back flat.",
    howTo: {
      setup: "Lie on your back, arms reaching toward the ceiling, knees bent at 90° over your hips.",
      steps: ["Slowly lower one arm overhead and the opposite leg toward the floor.", "Keep your lower back pressed flat.", "Return and switch sides."],
      mistakes: ["Letting the lower back arch off the floor.", "Moving too fast."],
      easier: "Move just the legs.", harder: "Lower limbs closer to the floor.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "bird-dog", name: "Bird Dog", emoji: "🐕", type: "strength",
    focus: ["core", "full"], muscles: ["core", "back"],
    muscleLabel: "Core · Lower Back", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "10 each side", defaultRest: 30,
    tip: "On all fours, extend opposite arm and leg, stay level.",
    howTo: {
      setup: "On hands and knees, wrists under shoulders, knees under hips.",
      steps: ["Extend one arm forward and the opposite leg back.", "Keep your hips and shoulders square to the floor.", "Return with control and switch sides."],
      mistakes: ["Twisting the hips.", "Arching the back."],
      easier: "Extend just an arm or just a leg.", harder: "Pause 2s at full extension.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "bicycle-crunch", name: "Bicycle Crunch", emoji: "🚲", type: "strength",
    focus: ["core"], muscles: ["core"],
    muscleLabel: "Abs · Obliques", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "20 reps", defaultRest: 30,
    tip: "Bring opposite elbow to knee, pedaling slowly with control.",
    howTo: {
      setup: "Lie on your back, hands lightly behind your head, knees lifted.",
      steps: ["Bring one knee in while rotating the opposite elbow toward it.", "Extend the other leg out.", "Alternate in a slow pedaling motion."],
      mistakes: ["Yanking on the neck.", "Rushing through reps."],
      easier: "Keep feet higher / slower pace.", harder: "Extend legs lower.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "side-plank", name: "Side Plank", emoji: "📐", type: "strength",
    focus: ["core"], muscles: ["core"],
    muscleLabel: "Obliques", equipment: ["bodyweight"], loaded: false,
    defaultSets: 2, defaultReps: "20s each side", defaultRest: 30, defaultDuration: 20,
    tip: "On one forearm, stack your body, lift your hips, hold.",
    howTo: {
      setup: "Lie on your side, forearm under your shoulder, legs stacked.",
      steps: ["Lift your hips so your body is a straight diagonal line.", "Hold, keeping your neck neutral.", "Switch sides halfway."],
      mistakes: ["Hips sagging toward the floor.", "Rotating forward."],
      easier: "Bottom knee on the floor.", harder: "Lift the top leg.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "russian-twist", name: "Russian Twist", emoji: "🌀", type: "strength",
    focus: ["core"], muscles: ["core"],
    muscleLabel: "Obliques", equipment: ["bodyweight", "dumbbell"], loaded: false,
    defaultSets: 3, defaultReps: "16 reps", defaultRest: 30,
    tip: "Lean back, feet up, rotate side to side with control.",
    howTo: {
      setup: "Sit with knees bent, lean back ~45°, feet hovering (or heels down to start).",
      steps: ["Clasp your hands (or hold a weight) at your chest.", "Rotate your torso to tap toward one hip, then the other.", "Keep your chest tall throughout."],
      mistakes: ["Rounding the back.", "Just moving the arms, not the torso."],
      easier: "Keep heels on the floor.", harder: "Hold a dumbbell and lift the feet.",
    },
    excludedBy: ["no-floor"],
  },

  // ============================== CARDIO ==============================
  {
    id: "high-knees", name: "High Knees", emoji: "🏃", type: "cardio",
    focus: ["cardio", "full", "core"], muscles: ["cardio", "core"],
    muscleLabel: "Heart Rate · Core", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "30 seconds", defaultRest: 30, defaultDuration: 30,
    tip: "Run in place driving your knees up to hip height, fast arms.",
    howTo: {
      setup: "Stand tall in a clear space, arms bent.",
      steps: ["Drive your knees up toward hip height alternately, fast.", "Stay on the balls of your feet.", "Pump your arms to match."],
      mistakes: ["Leaning back.", "Low knees — aim for hip height."],
      easier: "Slow it to a march.", harder: "Increase speed.",
    },
    excludedBy: ["no-jumping", "quiet", "knee-friendly"],
  },
  {
    id: "mountain-climber", name: "Mountain Climbers", emoji: "⛰️", type: "cardio",
    focus: ["cardio", "core", "full"], muscles: ["cardio", "core", "shoulders"],
    muscleLabel: "Core · Heart Rate", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "30 seconds", defaultRest: 30, defaultDuration: 30,
    tip: "In a plank, drive your knees toward your chest one at a time.",
    howTo: {
      setup: "Start in a high plank, hands under shoulders, body straight.",
      steps: ["Drive one knee toward your chest.", "Quickly switch legs in a running motion.", "Keep your hips low and level."],
      mistakes: ["Hips bouncing high.", "Hands creeping forward."],
      easier: "Slow, controlled steps.", harder: "Speed up.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "butt-kicks", name: "Butt Kicks", emoji: "🦵", type: "cardio",
    focus: ["cardio", "legs"], muscles: ["cardio", "hamstrings"],
    muscleLabel: "Heart Rate · Hamstrings", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "30 seconds", defaultRest: 30, defaultDuration: 30,
    tip: "Jog in place flicking your heels up toward your glutes.",
    howTo: {
      setup: "Stand tall, arms bent.",
      steps: ["Jog in place, kicking your heels up toward your glutes.", "Stay light on the balls of your feet.", "Keep a quick rhythm."],
      mistakes: ["Leaning forward.", "Slamming the feet down."],
      easier: "Slow the pace.", harder: "Quicken and lift heels higher.",
    },
    excludedBy: ["quiet", "knee-friendly"],
  },
  {
    id: "squat-to-press", name: "Squat to Press", emoji: "🏗️", type: "cardio",
    focus: ["cardio", "full", "legs"], muscles: ["fullbody", "shoulders", "quads"],
    muscleLabel: "Full Body Burner", equipment: ["bodyweight", "dumbbell"], loaded: false,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 40,
    tip: "Squat down, then stand and press your arms (or weights) overhead.",
    howTo: {
      setup: "Stand shoulder-width, hands at your shoulders (or dumbbells at shoulder height).",
      steps: ["Lower into a squat.", "Drive up powerfully through your heels.", "As you stand, press your hands/weights overhead.", "Return for the next rep."],
      mistakes: ["Pressing before fully standing.", "Arching the back at the top."],
      easier: "Bodyweight, smaller squat.", harder: "Add dumbbells.",
    },
  },
  {
    id: "skater-hops", name: "Skater Hops", emoji: "⛸️", type: "cardio",
    focus: ["cardio", "legs"], muscles: ["cardio", "glutes", "quads"],
    muscleLabel: "Heart Rate · Legs", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "30 seconds", defaultRest: 30, defaultDuration: 30,
    tip: "Bound side to side, landing softly on one leg like a speed skater.",
    howTo: {
      setup: "Stand on one leg, knee slightly bent.",
      steps: ["Push off sideways and land softly on the other foot.", "Let the trailing leg sweep behind you.", "Bound back and forth with control."],
      mistakes: ["Landing stiff-legged.", "Losing balance from going too wide."],
      easier: "Step side to side, no hop.", harder: "Bigger, faster bounds.",
    },
    excludedBy: ["no-jumping", "quiet", "knee-friendly"],
  },
  {
    id: "shadow-box", name: "Shadow Boxing", emoji: "🥊", type: "cardio",
    focus: ["cardio", "arms", "core"], muscles: ["cardio", "shoulders", "core"],
    muscleLabel: "Heart Rate · Shoulders", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "45 seconds", defaultRest: 30, defaultDuration: 45,
    tip: "Light on your feet, throw controlled punches, keep your core tight.",
    howTo: {
      setup: "Feet staggered, hands up by your chin, knees soft.",
      steps: ["Throw alternating jabs and crosses with controlled power.", "Rotate through your torso, not just the arms.", "Keep bouncing lightly on your feet."],
      mistakes: ["Locking the elbows on punches.", "Dropping your hands."],
      easier: "Slower punches, no bounce.", harder: "Add hooks and speed.",
    },
  },

  // ============================== COOLDOWNS ==============================
  {
    id: "quad-stretch", name: "Standing Quad Stretch", emoji: "🦵", type: "cooldown",
    focus: ["full", "legs", "cardio", "core", "arms"], muscles: ["mobility", "quads"],
    muscleLabel: "Quads", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30s each side", defaultRest: 0, defaultDuration: 30,
    tip: "Hold your foot behind you, stand tall, feel the front of your thigh.",
    howTo: {
      setup: "Stand tall, hold a wall for balance if needed.",
      steps: ["Bend one knee and grab that foot behind you.", "Gently pull your heel toward your glute.", "Keep your knees together; switch sides."],
      mistakes: ["Arching the back.", "Letting the knee splay out."],
      easier: "Use a strap/towel around the foot.", harder: "Hold longer, deeper.",
    },
  },
  {
    id: "hamstring-stretch", name: "Seated Hamstring Stretch", emoji: "🧘", type: "cooldown",
    focus: ["full", "legs", "cardio", "core"], muscles: ["mobility", "hamstrings"],
    muscleLabel: "Hamstrings", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Sit, reach for your toes, hold gently — no bouncing.",
    howTo: {
      setup: "Sit on the floor with legs extended in front of you.",
      steps: ["Hinge at the hips and reach toward your toes.", "Go to a gentle stretch, not pain.", "Breathe and hold; relax deeper on exhales."],
      mistakes: ["Bouncing to go further.", "Rounding hard through the neck."],
      easier: "Bend the knees slightly.", harder: "Reach past the toes.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "chest-opener", name: "Chest Opener Stretch", emoji: "🫸", type: "cooldown",
    focus: ["full", "arms", "core", "cardio"], muscles: ["mobility", "chest", "shoulders"],
    muscleLabel: "Chest · Shoulders", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Clasp your hands behind your back, open your chest toward the ceiling.",
    howTo: {
      setup: "Stand tall, clasp your hands together behind your back.",
      steps: ["Straighten your arms and lift your hands slightly.", "Open your chest and squeeze your shoulder blades.", "Hold and breathe."],
      mistakes: ["Shrugging shoulders up.", "Leaning forward."],
      easier: "Hold a towel between your hands.", harder: "Lift the hands higher.",
    },
  },
  {
    id: "childs-pose", name: "Child's Pose", emoji: "🧎", type: "cooldown",
    focus: ["full", "core", "legs", "arms", "cardio"], muscles: ["mobility", "back"],
    muscleLabel: "Back · Hips", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "40 seconds", defaultRest: 0, defaultDuration: 40,
    tip: "Kneel and reach forward, melt your chest toward the floor.",
    howTo: {
      setup: "Kneel on the floor, big toes together, knees apart.",
      steps: ["Sit your hips back toward your heels.", "Reach your arms forward and lower your chest.", "Rest your forehead down and breathe slowly."],
      mistakes: ["Holding tension in the shoulders.", "Forcing the hips down."],
      easier: "Place a cushion under your hips.", harder: "Walk hands further forward.",
    },
    excludedBy: ["no-floor", "knee-friendly"],
  },
  {
    id: "figure-four", name: "Figure-4 Glute Stretch", emoji: "4️⃣", type: "cooldown",
    focus: ["full", "legs", "cardio", "core"], muscles: ["mobility", "glutes"],
    muscleLabel: "Glutes · Hips", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30s each side", defaultRest: 0, defaultDuration: 30,
    tip: "Lie down, cross one ankle over the opposite knee, pull the thigh in.",
    howTo: {
      setup: "Lie on your back, knees bent, feet flat.",
      steps: ["Cross one ankle over the opposite thigh, making a '4'.", "Reach through and pull the bottom thigh toward your chest.", "Feel the stretch in the glute; switch sides."],
      mistakes: ["Lifting the head and straining the neck.", "Pulling into pain."],
      easier: "Keep the bottom foot on the floor.", harder: "Pull the thigh closer.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "shoulder-stretch", name: "Cross-Body Shoulder Stretch", emoji: "💆", type: "cooldown",
    focus: ["full", "arms", "core", "cardio"], muscles: ["mobility", "shoulders"],
    muscleLabel: "Shoulders", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30s each side", defaultRest: 0, defaultDuration: 30,
    tip: "Pull one straight arm across your chest with the other hand.",
    howTo: {
      setup: "Stand or sit tall.",
      steps: ["Bring one arm straight across your chest.", "Use the other hand to gently pull it closer.", "Hold, then switch arms."],
      mistakes: ["Shrugging the stretched shoulder.", "Bending the arm."],
      easier: "Lighter pull.", harder: "Hold a touch longer.",
    },
  },

  // ====================== EXPANDED WARMUPS (cross-functional) ======================
  {
    id: "jog-in-place", name: "Light Jog in Place", emoji: "🏃‍♂️", type: "warmup",
    focus: ["full", "legs", "arms", "core", "cardio"], muscles: ["cardio", "fullbody"],
    muscleLabel: "Whole Body · Heart Rate", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "60 seconds", defaultRest: 0, defaultDuration: 60,
    tip: "Easy jog on the spot — light on your feet, just warming the engine.",
    howTo: {
      setup: "Stand tall with relaxed shoulders, arms bent at 90°.",
      steps: ["Jog gently on the spot, landing softly on the balls of your feet.", "Let your arms swing naturally.", "Keep it easy — this is a warmup, not a sprint."],
      mistakes: ["Pounding the floor.", "Tensing the shoulders."],
      easier: "Drop to a brisk march.", harder: "Lift the knees a little higher.",
    },
  },
  {
    id: "shoulder-rolls", name: "Shoulder Rolls", emoji: "🔄", type: "warmup",
    focus: ["full", "legs", "arms", "core", "cardio"], muscles: ["shoulders", "mobility"],
    muscleLabel: "Shoulders · Mobility", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Roll shoulders up, back, and down in slow circles. Then reverse.",
    howTo: {
      setup: "Stand or sit tall, arms relaxed at your sides.",
      steps: ["Roll your shoulders up toward your ears, then back and down.", "Make big, slow circles.", "Reverse direction halfway through."],
      mistakes: ["Rushing the circles.", "Holding your breath."],
      easier: "Smaller circles.", harder: "Exaggerate the range.",
    },
  },
  {
    id: "torso-twists", name: "Standing Torso Twists", emoji: "🌀", type: "warmup",
    focus: ["full", "legs", "arms", "core", "cardio"], muscles: ["core", "mobility"],
    muscleLabel: "Core · Spine", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Rotate your torso side to side, letting your arms swing freely.",
    howTo: {
      setup: "Feet shoulder-width, knees soft, arms relaxed.",
      steps: ["Rotate your torso to one side, letting your arms swing around.", "Rotate to the other side.", "Keep your hips fairly still and pivot through the trunk."],
      mistakes: ["Twisting so hard you wrench the lower back.", "Locking the knees."],
      easier: "Smaller, slower twists.", harder: "Add a gentle reach with each twist.",
    },
  },
  {
    id: "hip-circles", name: "Hip Circles", emoji: "⭕", type: "warmup",
    focus: ["full", "legs", "core", "cardio"], muscles: ["glutes", "mobility"],
    muscleLabel: "Hips · Mobility", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Hands on hips, draw big circles with your hips. Switch directions.",
    howTo: {
      setup: "Feet shoulder-width, hands on your hips.",
      steps: ["Circle your hips clockwise, making the circle as big as is comfortable.", "After 15s, switch to counter-clockwise."],
      mistakes: ["Moving only the shoulders.", "Forcing the range."],
      easier: "Smaller circles.", harder: "Widen the circles.",
    },
  },
  {
    id: "inchworm-walkout", name: "Inchworm Walkout", emoji: "🐛", type: "warmup",
    focus: ["full", "core", "arms", "legs"], muscles: ["fullbody", "core", "mobility"],
    muscleLabel: "Full Body · Core", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "40 seconds", defaultRest: 0, defaultDuration: 40,
    tip: "Fold forward, walk hands out to a plank, walk them back, stand.",
    howTo: {
      setup: "Stand tall, feet hip-width.",
      steps: ["Hinge and place your hands on the floor.", "Walk your hands forward into a high plank.", "Walk your hands back to your feet and stand up."],
      mistakes: ["Letting the hips sag in the plank.", "Locking the knees hard."],
      easier: "Bend the knees and shorten the walkout.", harder: "Add a push-up at the plank.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "worlds-greatest-stretch", name: "World's Greatest Stretch", emoji: "🌎", type: "warmup",
    focus: ["full", "legs", "core", "cardio"], muscles: ["mobility", "hamstrings", "glutes"],
    muscleLabel: "Hips · Hamstrings · Spine", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "40 seconds", defaultRest: 0, defaultDuration: 40,
    tip: "Lunge, hand down, rotate the other arm to the ceiling. Alternate.",
    howTo: {
      setup: "Stand tall in a clear space.",
      steps: ["Step into a deep lunge and place both hands inside the front foot.", "Rotate one arm up toward the ceiling, opening your chest.", "Return and switch sides."],
      mistakes: ["Rushing the rotation.", "Letting the back knee slam down."],
      easier: "Shorten the lunge, hands on a low surface.", harder: "Hold the rotation 2s each rep.",
    },
    excludedBy: ["no-floor", "knee-friendly"],
  },
  {
    id: "lunge-with-twist", name: "Reverse Lunge with Twist", emoji: "🔁", type: "warmup",
    focus: ["legs", "full", "core", "cardio"], muscles: ["quads", "core", "mobility"],
    muscleLabel: "Legs · Core", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "40 seconds", defaultRest: 0, defaultDuration: 40,
    tip: "Step back into a lunge, then twist your torso over the front leg.",
    howTo: {
      setup: "Stand tall, hands at your chest.",
      steps: ["Step one foot back into a lunge.", "Gently rotate your torso toward the front leg.", "Return and alternate sides."],
      mistakes: ["Twisting from the lower back instead of the trunk.", "Front knee diving inward."],
      easier: "Smaller lunge, smaller twist.", harder: "Hold a light reach at the top of the twist.",
    },
    excludedBy: ["knee-friendly"],
  },
  {
    id: "knee-hugs", name: "Walking Knee Hugs", emoji: "🦵", type: "warmup",
    focus: ["full", "legs", "core", "cardio"], muscles: ["glutes", "mobility"],
    muscleLabel: "Hips · Glutes", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Pull one knee to your chest, stand tall, then switch.",
    howTo: {
      setup: "Stand tall, weight on one leg (hold a wall if needed).",
      steps: ["Lift one knee and hug it to your chest.", "Stand tall and balanced.", "Lower and switch legs."],
      mistakes: ["Rounding the back to reach the knee.", "Rushing and losing balance."],
      easier: "Hold a wall for balance.", harder: "Rise onto the toes of the standing foot.",
    },
  },
  {
    id: "ankle-bounces", name: "Ankle Bounces", emoji: "🦶", type: "warmup",
    focus: ["cardio", "legs", "full"], muscles: ["calves", "cardio"],
    muscleLabel: "Calves · Heart Rate", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Small, springy bounces on the balls of your feet.",
    howTo: {
      setup: "Stand tall, feet hip-width.",
      steps: ["Bounce lightly on the balls of your feet.", "Keep the bounces small and springy.", "Stay relaxed through the upper body."],
      mistakes: ["Landing flat and heavy.", "Bouncing too high."],
      easier: "Tiny heel raises, no bounce.", harder: "Quicken the tempo.",
    },
    excludedBy: ["quiet"],
  },
  {
    id: "standing-side-bend", name: "Standing Side Bend", emoji: "🤸", type: "warmup",
    focus: ["full", "legs", "arms", "core", "cardio"], muscles: ["core", "mobility"],
    muscleLabel: "Side Body · Obliques", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Reach one arm overhead and lean to the opposite side. Alternate.",
    howTo: {
      setup: "Stand tall, feet hip-width.",
      steps: ["Reach one arm overhead and lean to the opposite side.", "Feel a gentle stretch down your side.", "Return to center and switch sides."],
      mistakes: ["Leaning forward instead of sideways.", "Bouncing into the stretch."],
      easier: "Smaller lean, hand on hip.", harder: "Reach a touch further each rep.",
    },
  },
  {
    id: "plank-shoulder-taps-warm", name: "Plank Shoulder Taps", emoji: "🖐️", type: "warmup",
    focus: ["full", "core", "arms"], muscles: ["core", "shoulders"],
    muscleLabel: "Core · Shoulders", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "In a plank, tap each hand to the opposite shoulder without rocking.",
    howTo: {
      setup: "Start in a high plank, hands under shoulders, feet a bit wide for stability.",
      steps: ["Tap one hand to the opposite shoulder.", "Keep your hips as still as possible.", "Alternate hands at a steady pace."],
      mistakes: ["Hips rocking side to side.", "Hands drifting forward."],
      easier: "Drop to your knees.", harder: "Bring your feet closer together.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "neck-rolls", name: "Gentle Neck Rolls", emoji: "🙆", type: "warmup",
    focus: ["full", "legs", "arms", "core", "cardio"], muscles: ["mobility"],
    muscleLabel: "Neck · Mobility", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "25 seconds", defaultRest: 0, defaultDuration: 25,
    tip: "Slow half-circles, ear toward shoulder, chin toward chest.",
    howTo: {
      setup: "Sit or stand tall, shoulders relaxed.",
      steps: ["Drop one ear toward your shoulder.", "Roll your chin slowly down and across to the other side.", "Move gently — never force or crank the neck."],
      mistakes: ["Rolling the head all the way back.", "Moving too fast."],
      easier: "Just tilt ear-to-ear.", harder: "Add a slightly bigger arc.",
    },
  },
  {
    id: "dynamic-chest-opener", name: "Dynamic Chest Opener", emoji: "🦅", type: "warmup",
    focus: ["full", "arms", "core", "cardio"], muscles: ["chest", "shoulders", "mobility"],
    muscleLabel: "Chest · Shoulders", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Swing arms wide to open the chest, then cross them in front.",
    howTo: {
      setup: "Stand tall, arms out to the sides at shoulder height.",
      steps: ["Swing your arms wide and back to open the chest.", "Swing them forward and cross them over your chest.", "Build a smooth, rhythmic swing."],
      mistakes: ["Shrugging the shoulders up.", "Arching the lower back on the open."],
      easier: "Smaller swings.", harder: "Add a slight bounce at the open.",
    },
  },

  // ====================== EXPANDED COOLDOWNS ======================
  {
    id: "cobra-stretch", name: "Cobra Stretch", emoji: "🐍", type: "cooldown",
    focus: ["full", "core", "arms", "cardio", "legs"], muscles: ["chest", "back", "mobility"],
    muscleLabel: "Abs · Chest · Spine", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Lie face down, press your chest up, keep hips on the floor.",
    howTo: {
      setup: "Lie face down, hands under your shoulders, legs extended.",
      steps: ["Press gently through your hands to lift your chest.", "Keep your hips and pelvis on the floor.", "Relax your shoulders down and breathe."],
      mistakes: ["Cranking the lower back.", "Shrugging shoulders to the ears."],
      easier: "Prop on your forearms (sphinx).", harder: "Straighten the arms a little more.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "pigeon-stretch", name: "Pigeon Stretch", emoji: "🕊️", type: "cooldown",
    focus: ["full", "legs", "core", "cardio"], muscles: ["glutes", "mobility"],
    muscleLabel: "Glutes · Hips", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30s each side", defaultRest: 0, defaultDuration: 30,
    tip: "Front shin across, back leg long, fold forward gently.",
    howTo: {
      setup: "From all fours, bring one shin forward across your mat, back leg extended behind.",
      steps: ["Square your hips toward the floor.", "Walk your hands forward and fold over the front leg.", "Breathe into the glute stretch; switch sides."],
      mistakes: ["Collapsing onto one hip.", "Forcing the fold."],
      easier: "Stay more upright, or use a cushion under the hip.", harder: "Fold a little deeper.",
    },
    excludedBy: ["no-floor", "knee-friendly"],
  },
  {
    id: "butterfly-stretch", name: "Butterfly Stretch", emoji: "🦋", type: "cooldown",
    focus: ["full", "legs", "core"], muscles: ["glutes", "mobility"],
    muscleLabel: "Inner Thighs · Hips", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Soles of the feet together, gently press knees toward the floor.",
    howTo: {
      setup: "Sit tall, bring the soles of your feet together, knees out.",
      steps: ["Hold your feet and sit up tall.", "Let your knees relax toward the floor.", "Gently lean forward from the hips for more."],
      mistakes: ["Rounding the back hard.", "Bouncing the knees."],
      easier: "Move your feet further from your body.", harder: "Lean forward a little more.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "lying-spinal-twist", name: "Lying Spinal Twist", emoji: "🔄", type: "cooldown",
    focus: ["full", "legs", "arms", "core", "cardio"], muscles: ["back", "core", "mobility"],
    muscleLabel: "Spine · Lower Back", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30s each side", defaultRest: 0, defaultDuration: 30,
    tip: "On your back, drop both knees to one side, arms wide.",
    howTo: {
      setup: "Lie on your back, arms out in a T, knees bent.",
      steps: ["Let both knees fall gently to one side.", "Turn your head the opposite way if it's comfortable.", "Breathe, then switch sides."],
      mistakes: ["Forcing the knees down.", "Lifting the shoulders off the floor."],
      easier: "Place a cushion under the knees.", harder: "Draw the knees higher toward the chest.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "standing-forward-fold", name: "Standing Forward Fold", emoji: "🙇", type: "cooldown",
    focus: ["full", "legs", "arms", "core", "cardio"], muscles: ["hamstrings", "back", "mobility"],
    muscleLabel: "Hamstrings · Back", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Hinge and hang forward, soft knees, let your head go heavy.",
    howTo: {
      setup: "Stand tall, feet hip-width.",
      steps: ["Hinge at the hips and fold forward.", "Let your arms and head hang heavy, knees soft.", "Sway gently and breathe."],
      mistakes: ["Locking the knees hard.", "Rounding aggressively to reach the floor."],
      easier: "Bend the knees generously.", harder: "Gently straighten the legs.",
    },
  },
  {
    id: "neck-stretch", name: "Neck Stretch", emoji: "💆‍♂️", type: "cooldown",
    focus: ["full", "legs", "arms", "core", "cardio"], muscles: ["mobility"],
    muscleLabel: "Neck · Traps", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30s each side", defaultRest: 0, defaultDuration: 30,
    tip: "Ease one ear toward your shoulder, hand resting on your head.",
    howTo: {
      setup: "Sit or stand tall.",
      steps: ["Tilt one ear toward your shoulder.", "Rest that hand lightly on your head for a gentle assist.", "Hold, breathe, switch sides."],
      mistakes: ["Pulling hard on the head.", "Shrugging the opposite shoulder."],
      easier: "No hand — just the tilt.", harder: "Let the hand add a touch more weight.",
    },
  },
  {
    id: "overhead-triceps-stretch", name: "Overhead Triceps Stretch", emoji: "🙆‍♀️", type: "cooldown",
    focus: ["full", "arms", "core"], muscles: ["triceps", "shoulders", "mobility"],
    muscleLabel: "Triceps · Shoulders", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30s each side", defaultRest: 0, defaultDuration: 30,
    tip: "Reach a hand down your back, gently press the elbow with the other hand.",
    howTo: {
      setup: "Stand or sit tall.",
      steps: ["Reach one hand down your upper back, elbow pointing up.", "Use the other hand to gently press the elbow.", "Hold, breathe, switch sides."],
      mistakes: ["Arching the back to compensate.", "Forcing the elbow."],
      easier: "Lighter press.", harder: "Ease a little deeper.",
    },
  },
  {
    id: "lat-side-reach", name: "Side Lat Reach", emoji: "🌿", type: "cooldown",
    focus: ["full", "arms", "core", "cardio"], muscles: ["back", "mobility"],
    muscleLabel: "Lats · Side Body", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30s each side", defaultRest: 0, defaultDuration: 30,
    tip: "Reach overhead and lean to one side, feeling the stretch down your lat.",
    howTo: {
      setup: "Stand tall, feet hip-width.",
      steps: ["Reach one arm overhead.", "Lean to the opposite side and hold.", "Breathe into the side stretch; switch sides."],
      mistakes: ["Twisting forward.", "Bouncing."],
      easier: "Smaller lean.", harder: "Reach a touch further.",
    },
  },
  {
    id: "wall-calf-stretch", name: "Wall Calf Stretch", emoji: "🧱", type: "cooldown",
    focus: ["full", "legs", "cardio"], muscles: ["calves", "mobility"],
    muscleLabel: "Calves", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30s each side", defaultRest: 0, defaultDuration: 30,
    tip: "Hands on a wall, one leg back, heel down, lean in.",
    howTo: {
      setup: "Face a wall, hands at chest height, one foot stepped back.",
      steps: ["Keep the back leg straight and the heel pressed down.", "Lean toward the wall until you feel the calf stretch.", "Hold, breathe, switch sides."],
      mistakes: ["Letting the back heel lift.", "Bouncing into it."],
      easier: "Shorten the stance.", harder: "Step the back foot further away.",
    },
  },
  {
    id: "happy-baby", name: "Happy Baby", emoji: "👶", type: "cooldown",
    focus: ["full", "legs", "core"], muscles: ["glutes", "mobility"],
    muscleLabel: "Hips · Lower Back", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "On your back, hold the outsides of your feet, knees toward armpits.",
    howTo: {
      setup: "Lie on your back.",
      steps: ["Draw your knees toward your chest and grab the outsides of your feet.", "Gently pull your knees toward your armpits.", "Rock side to side and breathe."],
      mistakes: ["Lifting the head and shoulders to reach.", "Forcing the knees down."],
      easier: "Hold behind the thighs instead of the feet.", harder: "Ease the knees a little wider/lower.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "deep-breathing", name: "Deep Breathing", emoji: "🌬️", type: "cooldown",
    focus: ["full", "legs", "arms", "core", "cardio"], muscles: ["mobility"],
    muscleLabel: "Recovery · Breath", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "40 seconds", defaultRest: 0, defaultDuration: 40,
    tip: "Slow breaths — in through the nose, out through the mouth.",
    howTo: {
      setup: "Stand or sit tall, or lie down, hands relaxed.",
      steps: ["Inhale slowly through your nose for a count of four.", "Exhale gently through your mouth for a count of six.", "Let your heart rate settle and your muscles relax."],
      mistakes: ["Breathing shallow and fast.", "Tensing the shoulders on the inhale."],
      easier: "Just breathe at a comfortable slow pace.", harder: "Lengthen the exhale further.",
    },
  },

  // ====================== EXPANDED LEGS ======================
  {
    id: "bulgarian-split-squat", name: "Bulgarian Split Squat", emoji: "🦵", type: "strength",
    focus: ["legs", "full"], muscles: ["quads", "glutes"],
    muscleLabel: "Quads · Glutes", equipment: ["bodyweight", "dumbbell"], loaded: false,
    defaultSets: 3, defaultReps: "10 each side", defaultRest: 45,
    tip: "Back foot on a bench behind you, lower straight down, drive up.",
    howTo: {
      setup: "Stand a stride in front of a bench, rest the top of one foot on it behind you.",
      steps: ["Lower straight down, bending the front knee.", "Keep your front shin fairly vertical.", "Drive through the front heel to stand; switch legs."],
      mistakes: ["Leaning too far forward.", "Front knee caving inward."],
      easier: "Hold a wall and use bodyweight.", harder: "Hold dumbbells.",
    },
    excludedBy: ["knee-friendly"],
  },
  {
    id: "sumo-squat", name: "Sumo Squat", emoji: "🟢", type: "strength",
    focus: ["legs", "full"], muscles: ["quads", "glutes", "hamstrings"],
    muscleLabel: "Glutes · Inner Thighs", equipment: ["bodyweight", "dumbbell"], loaded: false,
    defaultSets: 3, defaultReps: "15 reps", defaultRest: 40,
    tip: "Wide stance, toes out, sit straight down, squeeze glutes up.",
    howTo: {
      setup: "Stand with a wide stance, toes turned out ~45° (optionally a dumbbell held at your chest).",
      steps: ["Sit straight down, knees tracking over your toes.", "Lower until thighs are about parallel.", "Drive up and squeeze your glutes."],
      mistakes: ["Knees caving inward.", "Leaning the chest forward."],
      easier: "Bodyweight, smaller depth.", harder: "Hold a dumbbell.",
    },
  },
  {
    id: "lateral-lunge", name: "Lateral Lunge", emoji: "↔️", type: "strength",
    focus: ["legs", "full"], muscles: ["quads", "glutes"],
    muscleLabel: "Quads · Inner Thighs", equipment: ["bodyweight", "dumbbell"], loaded: false,
    defaultSets: 3, defaultReps: "10 each side", defaultRest: 40,
    tip: "Step wide to one side, sit back into that hip, other leg straight.",
    howTo: {
      setup: "Stand tall, feet together.",
      steps: ["Take a wide step to one side.", "Push your hips back and bend that knee while the other leg stays straight.", "Push back to the center; alternate sides."],
      mistakes: ["Bending knee past the toes.", "Rounding the back."],
      easier: "Shorten the step.", harder: "Hold a dumbbell at your chest.",
    },
    excludedBy: ["knee-friendly"],
  },
  {
    id: "single-leg-glute-bridge", name: "Single-Leg Glute Bridge", emoji: "🌉", type: "strength",
    focus: ["legs", "core"], muscles: ["glutes", "hamstrings", "core"],
    muscleLabel: "Glutes · Hamstrings", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "10 each side", defaultRest: 35,
    tip: "Bridge up driving through one heel, other leg extended.",
    howTo: {
      setup: "Lie on your back, knees bent; extend one leg straight.",
      steps: ["Press through the planted heel to lift your hips.", "Keep your hips level — don't let one side drop.", "Lower with control; switch legs."],
      mistakes: ["Hips tilting to one side.", "Over-arching the lower back."],
      easier: "Do a regular two-leg bridge.", harder: "Pause 2s at the top.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "good-morning", name: "Dumbbell Good Morning", emoji: "🌅", type: "strength",
    focus: ["legs", "full"], muscles: ["hamstrings", "back", "glutes"],
    muscleLabel: "Hamstrings · Lower Back", equipment: ["dumbbell", "bands"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 40,
    tip: "Weight at your chest, hinge forward with a flat back, return tall.",
    howTo: {
      setup: "Hold a dumbbell at your chest (or a band under your feet, over your shoulders), feet hip-width, knees soft.",
      steps: ["Push your hips back and hinge your torso forward.", "Keep your back flat and stop around parallel.", "Drive your hips forward to stand tall."],
      mistakes: ["Rounding the back.", "Turning it into a squat."],
      easier: "Bodyweight, smaller range.", harder: "Slow the hinge to 3s.",
    },
  },
  {
    id: "curtsy-lunge", name: "Curtsy Lunge", emoji: "💃", type: "strength",
    focus: ["legs"], muscles: ["quads", "glutes"],
    muscleLabel: "Glutes · Quads", equipment: ["bodyweight", "dumbbell"], loaded: false,
    defaultSets: 3, defaultReps: "10 each side", defaultRest: 40,
    tip: "Step one leg diagonally behind the other and lower into a lunge.",
    howTo: {
      setup: "Stand tall, hands at your chest.",
      steps: ["Step one foot diagonally behind and across the other.", "Lower until both knees are bent.", "Return to standing; alternate sides."],
      mistakes: ["Front knee caving in.", "Twisting the hips open."],
      easier: "Shorten the step, hold a wall.", harder: "Hold dumbbells.",
    },
    excludedBy: ["knee-friendly"],
  },

  // ====================== EXPANDED ARMS / UPPER ======================
  {
    id: "skullcrusher", name: "Dumbbell Skullcrusher", emoji: "💀", type: "strength",
    focus: ["arms"], muscles: ["triceps"],
    muscleLabel: "Triceps", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 35,
    tip: "Lying down, lower the dumbbells toward your forehead, then extend.",
    howTo: {
      setup: "Lie on a bench or floor, dumbbells pressed up over your chest, palms facing each other.",
      steps: ["Keeping your upper arms still, bend your elbows to lower the weights toward your forehead.", "Stop just above your head.", "Extend back up by straightening your elbows."],
      mistakes: ["Moving the upper arms.", "Flaring the elbows wide."],
      easier: "Lighter weight.", harder: "Slow the lowering to 3s.",
    },
  },
  {
    id: "arnold-press", name: "Arnold Press", emoji: "💪", type: "strength",
    focus: ["arms", "full"], muscles: ["shoulders", "triceps"],
    muscleLabel: "Shoulders · Triceps", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "10 reps", defaultRest: 45,
    tip: "Start palms facing you, rotate out as you press overhead.",
    howTo: {
      setup: "Sit or stand tall, dumbbells at chest height with palms facing you.",
      steps: ["Press the weights up while rotating your palms to face forward.", "Finish with arms extended overhead.", "Reverse the rotation on the way down."],
      mistakes: ["Arching the lower back.", "Rushing the rotation."],
      easier: "Lighter weight or one arm at a time.", harder: "Slow, controlled tempo.",
    },
    excludedBy: ["shoulder-friendly"],
  },
  {
    id: "front-raise", name: "Front Raise", emoji: "🙋", type: "strength",
    focus: ["arms"], muscles: ["shoulders"],
    muscleLabel: "Front Delts", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 30,
    tip: "Raise the dumbbells straight in front to shoulder height.",
    howTo: {
      setup: "Stand tall, dumbbells in front of your thighs, palms facing you.",
      steps: ["Raise the weights straight in front to shoulder height.", "Keep a slight bend in the elbows.", "Lower slowly with control."],
      mistakes: ["Swinging the body to lift.", "Raising above shoulder height."],
      easier: "Very light weight, one arm at a time.", harder: "Pause at the top.",
    },
    excludedBy: ["shoulder-friendly"],
  },
  {
    id: "concentration-curl", name: "Concentration Curl", emoji: "🎯", type: "strength",
    focus: ["arms"], muscles: ["biceps"],
    muscleLabel: "Biceps", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "10 each side", defaultRest: 30,
    tip: "Seated, elbow braced on your thigh, curl with full control.",
    howTo: {
      setup: "Sit, lean forward slightly, brace your working elbow against the inside of your thigh.",
      steps: ["Curl the dumbbell up, squeezing the biceps.", "Keep the upper arm still against your thigh.", "Lower slowly to full extension; switch sides."],
      mistakes: ["Swinging the weight up.", "Lifting the elbow off the thigh."],
      easier: "Lighter weight.", harder: "3s lowering tempo.",
    },
  },
  {
    id: "pike-pushup", name: "Pike Push-Up", emoji: "🔺", type: "strength",
    focus: ["arms", "full"], muscles: ["shoulders", "triceps"],
    muscleLabel: "Shoulders · Triceps", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "8 reps", defaultRest: 45,
    tip: "Hips high in an upside-down V, lower the crown of your head toward the floor.",
    howTo: {
      setup: "Start in a downward-dog shape: hips high, hands and feet on the floor, body in an inverted V.",
      steps: ["Bend your elbows to lower the top of your head toward the floor.", "Keep your hips high throughout.", "Press back up to the start."],
      mistakes: ["Letting the hips drop into a plank.", "Flaring the elbows wide."],
      easier: "Smaller range, or do shoulder taps instead.", harder: "Elevate your feet slightly.",
    },
    excludedBy: ["shoulder-friendly", "no-floor"],
  },
  {
    id: "diamond-pushup", name: "Diamond Push-Up", emoji: "💎", type: "strength",
    focus: ["arms"], muscles: ["triceps", "chest"],
    muscleLabel: "Triceps · Chest", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "8 reps", defaultRest: 45,
    tip: "Hands close together forming a diamond, elbows tuck back.",
    howTo: {
      setup: "High plank with your hands close together under your chest, index fingers and thumbs touching.",
      steps: ["Lower your chest toward your hands, elbows tucking close to your body.", "Keep a straight line head to heels.", "Press back up."],
      mistakes: ["Hips sagging.", "Elbows flaring out wide."],
      easier: "Drop to your knees.", harder: "Slow the lowering.",
    },
    excludedBy: ["no-floor"],
  },

  // ====================== EXPANDED CORE ======================
  {
    id: "hollow-hold", name: "Hollow Hold", emoji: "🌙", type: "strength",
    focus: ["core"], muscles: ["core"],
    muscleLabel: "Deep Core", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "20 seconds", defaultRest: 30, defaultDuration: 20,
    tip: "On your back, press your low back down, lift shoulders and legs slightly.",
    howTo: {
      setup: "Lie on your back, arms reaching overhead, legs straight.",
      steps: ["Press your lower back flat into the floor.", "Lift your shoulders and legs a few inches.", "Hold the dish shape and breathe."],
      mistakes: ["Lower back arching off the floor.", "Holding your breath."],
      easier: "Bend the knees and/or keep arms by your sides.", harder: "Lower the legs closer to the floor.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "flutter-kicks", name: "Flutter Kicks", emoji: "🦶", type: "strength",
    focus: ["core"], muscles: ["core"],
    muscleLabel: "Lower Abs", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "30 seconds", defaultRest: 30, defaultDuration: 30,
    tip: "On your back, small fast scissor kicks, low back pressed down.",
    howTo: {
      setup: "Lie on your back, hands under your hips, legs extended.",
      steps: ["Lift both legs a few inches off the floor.", "Make small, quick up-and-down scissor kicks.", "Keep your lower back pressed into the floor."],
      mistakes: ["Lower back arching up.", "Kicking too big and slow."],
      easier: "Raise the legs higher / smaller range.", harder: "Lower the legs closer to the floor.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "v-up", name: "V-Up", emoji: "✅", type: "strength",
    focus: ["core"], muscles: ["core"],
    muscleLabel: "Abs", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 35,
    tip: "Lift legs and torso together to form a V, reaching for your toes.",
    howTo: {
      setup: "Lie flat on your back, arms extended overhead.",
      steps: ["Simultaneously lift your legs and upper body, reaching toward your toes.", "Form a V shape and balance on your hips.", "Lower with control."],
      mistakes: ["Yanking the neck.", "Using momentum instead of control."],
      easier: "Do a tuck (bend the knees in) instead.", harder: "Slow the lowering.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "reverse-crunch", name: "Reverse Crunch", emoji: "🔃", type: "strength",
    focus: ["core"], muscles: ["core"],
    muscleLabel: "Lower Abs", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "15 reps", defaultRest: 30,
    tip: "Knees over hips, curl your hips up off the floor toward your chest.",
    howTo: {
      setup: "Lie on your back, hands by your sides, knees bent over your hips.",
      steps: ["Curl your hips and knees up toward your chest.", "Lift your hips slightly off the floor.", "Lower slowly without swinging."],
      mistakes: ["Swinging the legs for momentum.", "Pulling with the neck."],
      easier: "Smaller lift.", harder: "Straighten the legs a bit more.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "leg-raise", name: "Lying Leg Raise", emoji: "📏", type: "strength",
    focus: ["core"], muscles: ["core"],
    muscleLabel: "Lower Abs", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 35,
    tip: "Legs straight, lower them slowly without arching your back.",
    howTo: {
      setup: "Lie on your back, hands under your hips, legs straight.",
      steps: ["Keeping legs fairly straight, lift them to vertical.", "Lower slowly toward the floor.", "Stop before your lower back arches up."],
      mistakes: ["Lower back peeling off the floor.", "Dropping the legs fast."],
      easier: "Bend the knees / smaller range.", harder: "Lower closer to the floor and pause.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "plank-shoulder-tap", name: "Plank Shoulder Taps", emoji: "🤚", type: "strength",
    focus: ["core", "full", "arms"], muscles: ["core", "shoulders"],
    muscleLabel: "Core · Shoulders", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "20 reps", defaultRest: 30,
    tip: "In a plank, tap each hand to the opposite shoulder, hips steady.",
    howTo: {
      setup: "High plank, hands under shoulders, feet a bit wide for stability.",
      steps: ["Tap one hand to the opposite shoulder.", "Resist rocking your hips.", "Alternate hands with control."],
      mistakes: ["Hips swaying side to side.", "Rushing the taps."],
      easier: "Drop to your knees.", harder: "Bring the feet closer together.",
    },
    excludedBy: ["no-floor"],
  },

  // ====================== EXPANDED FULL BODY / BACK / CHEST ======================
  {
    id: "superman", name: "Superman", emoji: "🦸", type: "strength",
    focus: ["full", "core"], muscles: ["back", "glutes"],
    muscleLabel: "Lower Back · Glutes", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 30,
    tip: "Face down, lift arms, chest, and legs off the floor; squeeze; lower.",
    howTo: {
      setup: "Lie face down, arms extended in front of you.",
      steps: ["Lift your arms, chest, and legs off the floor.", "Squeeze your glutes and back.", "Lower with control."],
      mistakes: ["Cranking the neck up.", "Jerking into the lift."],
      easier: "Lift just the upper body or just the legs.", harder: "Hold 2s at the top.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "incline-pushup", name: "Incline Push-Up", emoji: "📐", type: "strength",
    focus: ["full", "arms", "core"], muscles: ["chest", "triceps", "shoulders"],
    muscleLabel: "Chest · Triceps", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 35,
    tip: "Hands on a bench or counter, push up at an angle — beginner friendly.",
    howTo: {
      setup: "Place your hands on a sturdy bench, counter, or wall; walk your feet back to a straight line.",
      steps: ["Lower your chest toward the surface.", "Keep your body straight, elbows ~45°.", "Press back up."],
      mistakes: ["Hips sagging or piking.", "Flaring elbows straight out."],
      easier: "Use a higher surface (counter or wall).", harder: "Use a lower surface.",
    },
  },
  {
    id: "renegade-row", name: "Renegade Row", emoji: "🚣‍♀️", type: "strength",
    focus: ["full", "arms", "core"], muscles: ["back", "core", "biceps"],
    muscleLabel: "Back · Core", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "10 each side", defaultRest: 45,
    tip: "In a plank on dumbbells, row one to your hip while keeping hips steady.",
    howTo: {
      setup: "Start in a high plank gripping a dumbbell in each hand, feet wide for stability.",
      steps: ["Row one dumbbell up toward your hip.", "Keep your hips square to the floor — resist twisting.", "Lower and switch sides."],
      mistakes: ["Hips rotating with each row.", "Letting the lower back sag."],
      easier: "Drop to your knees, or row without weight.", harder: "Bring the feet closer.",
    },
    excludedBy: ["no-floor"],
  },

  // ====================== EXPANDED CARDIO ======================
  {
    id: "burpee", name: "Burpee", emoji: "🔥", type: "cardio",
    focus: ["cardio", "full"], muscles: ["fullbody", "cardio"],
    muscleLabel: "Full Body Burner", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "10 reps", defaultRest: 45,
    tip: "Squat, hands down, jump feet back, (push-up), jump feet in, hop up.",
    howTo: {
      setup: "Stand tall in a clear space.",
      steps: ["Squat and place your hands on the floor.", "Jump your feet back to a plank (add a push-up if you like).", "Jump your feet back in and explode up with a hop."],
      mistakes: ["Sagging hips in the plank.", "Landing stiff-legged on the hop."],
      easier: "Step the feet back/in and skip the hop.", harder: "Add a push-up every rep.",
    },
    excludedBy: ["no-jumping", "quiet", "knee-friendly", "no-floor"],
  },
  {
    id: "jump-squat", name: "Jump Squat", emoji: "⬆️", type: "cardio",
    focus: ["cardio", "legs", "full"], muscles: ["quads", "glutes", "cardio"],
    muscleLabel: "Legs · Power", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 40,
    tip: "Squat down, then jump explosively, landing soft into the next squat.",
    howTo: {
      setup: "Stand shoulder-width, arms ready to swing.",
      steps: ["Lower into a squat.", "Jump up explosively, swinging your arms.", "Land softly with bent knees straight into the next rep."],
      mistakes: ["Landing stiff and loud.", "Knees caving on landing."],
      easier: "Do bodyweight squats (no jump).", harder: "Pause briefly at the bottom each rep.",
    },
    excludedBy: ["no-jumping", "quiet", "knee-friendly"],
  },
  {
    id: "fast-feet", name: "Fast Feet", emoji: "👟", type: "cardio",
    focus: ["cardio", "full", "legs"], muscles: ["cardio", "quads"],
    muscleLabel: "Heart Rate · Agility", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "30 seconds", defaultRest: 30, defaultDuration: 30,
    tip: "Tiny, rapid steps on the balls of your feet, staying low.",
    howTo: {
      setup: "Sit into a quarter-squat, weight on the balls of your feet.",
      steps: ["Run your feet as fast as you can in tiny steps.", "Stay low with a flat back.", "Pump your arms to match the rhythm."],
      mistakes: ["Standing up tall (losing the athletic stance).", "Slamming the feet."],
      easier: "Slower tempo, stand a bit taller.", harder: "Go faster and lower.",
    },
    excludedBy: ["quiet"],
  },
  {
    id: "lateral-shuffle", name: "Lateral Shuffle", emoji: "↔️", type: "cardio",
    focus: ["cardio", "legs"], muscles: ["cardio", "glutes", "quads"],
    muscleLabel: "Heart Rate · Legs", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "30 seconds", defaultRest: 30, defaultDuration: 30,
    tip: "Stay low and shuffle side to side a few steps each way.",
    howTo: {
      setup: "Sit into a quarter-squat, chest up.",
      steps: ["Shuffle a few quick steps to one side.", "Then shuffle back to the other side.", "Stay low and light the whole time."],
      mistakes: ["Standing up between shuffles.", "Crossing the feet."],
      easier: "Slow, smaller shuffles.", harder: "Widen the distance and speed up.",
    },
    excludedBy: ["quiet"],
  },
  {
    id: "plank-jacks", name: "Plank Jacks", emoji: "🧱", type: "cardio",
    focus: ["cardio", "core", "full"], muscles: ["core", "cardio", "shoulders"],
    muscleLabel: "Core · Heart Rate", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "30 seconds", defaultRest: 30, defaultDuration: 30,
    tip: "Hold a plank and jump your feet wide and together, like a jack.",
    howTo: {
      setup: "Start in a forearm or high plank, feet together.",
      steps: ["Jump both feet out wide.", "Jump them back together.", "Keep your hips level and core tight throughout."],
      mistakes: ["Hips bouncing up.", "Sagging the lower back."],
      easier: "Step the feet out/in instead of jumping.", harder: "Speed up the tempo.",
    },
    excludedBy: ["no-floor", "quiet"],
  },
  {
    id: "seal-jacks", name: "Seal Jacks", emoji: "🦭", type: "cardio",
    focus: ["cardio", "full", "arms"], muscles: ["cardio", "shoulders", "chest"],
    muscleLabel: "Heart Rate · Chest", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "30 seconds", defaultRest: 30, defaultDuration: 30,
    tip: "Like jumping jacks, but arms come straight forward and clap.",
    howTo: {
      setup: "Stand tall, arms extended straight out to the sides at shoulder height.",
      steps: ["Jump your feet out as you bring your arms forward to clap.", "Jump your feet back as your arms open wide.", "Keep a steady rhythm."],
      mistakes: ["Landing heavy and flat.", "Shrugging the shoulders."],
      easier: "Step out one foot at a time (no jump).", harder: "Quicken the pace.",
    },
    excludedBy: ["no-jumping", "quiet"],
  },
];

export const EXERCISE_MAP: Record<string, Exercise> = Object.fromEntries(
  EXERCISES.map((e) => [e.id, e])
);

export function getExercise(id: string): Exercise | undefined {
  return EXERCISE_MAP[id];
}
