import type { Exercise } from "./types";

// Curated, beginner-first exercise library. Every entry carries a plain-English
// howTo so a newcomer can execute it without prior knowledge. Equipment tiers
// list where an exercise is available; the generator intersects them with what
// the user says they have (see generator.ts -> allowedTiers).

export const EXERCISES: Exercise[] = [
  // ============================== WARMUPS ==============================
  {
    id: "march-in-place", name: "March in Place", emoji: "🚶", type: "warmup",
    focus: ["full", "legs", "arms", "core", "cardio"], muscles: ["cardio", "mobility"],
    muscleLabel: "Full Body · Heart Rate", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "60 seconds", defaultRest: 0, defaultDuration: 60,
    tip: "Lift knees to hip height, pump your arms. Get the blood moving.",
    howTo: {
      setup: "Stand tall in a clear space, feet hip-width apart, arms bent at 90°.",
      steps: ["Drive one knee up toward hip height.", "Lower it and drive the other knee up.", "Swing opposite arm with each knee, building a steady rhythm."],
      mistakes: ["Hunching forward — stay tall.", "Going too fast too soon — this is a warmup."],
      easier: "Keep knees low and slow.", harder: "Lift knees higher and quicken the pace.",
    },
  },
  {
    id: "arm-circles", name: "Arm Circles", emoji: "🔄", type: "warmup",
    focus: ["full", "arms", "core"], muscles: ["shoulders", "mobility"],
    muscleLabel: "Shoulders · Mobility", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Big slow circles forward, then backward. Loosen the shoulders.",
    howTo: {
      setup: "Stand with feet shoulder-width, arms extended straight out to the sides.",
      steps: ["Draw small circles forward, gradually widening them.", "After 15s, reverse direction and circle backward."],
      mistakes: ["Shrugging shoulders up to ears — keep them down.", "Bending the elbows."],
      easier: "Smaller circles.", harder: "Larger, slower circles for more range.",
    },
  },
  {
    id: "bodyweight-squat-warm", name: "Bodyweight Squats", emoji: "🦵", type: "warmup",
    focus: ["full", "legs", "core"], muscles: ["quads", "glutes", "mobility"],
    muscleLabel: "Legs · Mobility", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "40 seconds", defaultRest: 0, defaultDuration: 40,
    tip: "Feet shoulder-width, chest up, sit back into your heels.",
    howTo: {
      setup: "Feet shoulder-width apart, toes slightly out, arms reaching forward for balance.",
      steps: ["Push hips back as if sitting into a chair.", "Lower until thighs are roughly parallel to the floor.", "Drive through your heels to stand tall."],
      mistakes: ["Knees caving inward.", "Lifting heels off the floor."],
      easier: "Squat to a chair and tap it.", harder: "Slow the lowering to 3 seconds.",
    },
  },
  {
    id: "leg-swings", name: "Leg Swings", emoji: "🦿", type: "warmup",
    focus: ["legs", "full", "cardio"], muscles: ["hamstrings", "glutes", "mobility"],
    muscleLabel: "Hips · Hamstrings", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Hold a wall, swing one leg front-to-back like a pendulum.",
    howTo: {
      setup: "Stand beside a wall for support, weight on one leg.",
      steps: ["Swing the free leg forward and back in a controlled arc.", "Keep your torso upright.", "Switch legs halfway through."],
      mistakes: ["Swinging so hard you lose balance.", "Rounding the back."],
      easier: "Smaller swings.", harder: "Add a gentle side-to-side swing too.",
    },
    excludedBy: [],
  },
  {
    id: "jumping-jacks", name: "Jumping Jacks", emoji: "⭐", type: "warmup",
    focus: ["full", "cardio", "legs"], muscles: ["cardio", "fullbody"],
    muscleLabel: "Full Body · Heart Rate", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Jump feet wide while raising arms overhead, then back. Stay light.",
    howTo: {
      setup: "Stand tall, feet together, arms at your sides.",
      steps: ["Jump feet out wide while sweeping arms overhead.", "Jump back to start, arms down.", "Keep a steady bouncing rhythm."],
      mistakes: ["Landing flat and heavy — land soft on the balls of your feet."],
      easier: "Step out one foot at a time (no jump).", harder: "Quicken the pace.",
    },
    excludedBy: ["no-jumping", "quiet"],
  },
  {
    id: "cat-cow", name: "Cat-Cow", emoji: "🐈", type: "warmup",
    focus: ["core", "full"], muscles: ["core", "back", "mobility"],
    muscleLabel: "Spine · Core Mobility", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "On all fours, alternate arching and rounding your back slowly.",
    howTo: {
      setup: "On hands and knees, wrists under shoulders, knees under hips.",
      steps: ["Drop your belly and lift your gaze (cow).", "Round your spine toward the ceiling and tuck your chin (cat).", "Flow slowly with your breath."],
      mistakes: ["Rushing — move with control.", "Forcing the range."],
      easier: "Smaller movements.", harder: "Pause and breathe at each end.",
    },
    excludedBy: ["no-floor"],
  },

  // ============================== LEGS ==============================
  {
    id: "goblet-squat", name: "Goblet Squat", emoji: "🏋️", type: "strength",
    focus: ["legs", "full"], muscles: ["quads", "glutes", "core"],
    muscleLabel: "Quads · Glutes · Core", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 45,
    tip: "Hold a dumbbell at your chest. Squat deep, keep your chest tall.",
    howTo: {
      setup: "Hold one dumbbell vertically against your chest with both hands, feet shoulder-width.",
      steps: ["Push your hips back and bend your knees.", "Lower until thighs are parallel, elbows tracking inside knees.", "Drive through your heels to stand."],
      mistakes: ["Letting the chest collapse forward.", "Knees caving in."],
      easier: "Use a lighter weight or bodyweight only.", harder: "Pause 2s at the bottom.",
    },
    excludedBy: ["knee-friendly"],
  },
  {
    id: "reverse-lunge", name: "Reverse Lunge", emoji: "🚶‍♂️", type: "strength",
    focus: ["legs", "full"], muscles: ["quads", "glutes", "hamstrings"],
    muscleLabel: "Quads · Glutes", equipment: ["bodyweight", "dumbbell"], loaded: false,
    defaultSets: 3, defaultReps: "10 each side", defaultRest: 45,
    tip: "Step back, drop the back knee toward the floor, then drive up.",
    howTo: {
      setup: "Stand tall, hands on hips (or a dumbbell in each hand).",
      steps: ["Step one foot back and lower until both knees are ~90°.", "Keep your front shin vertical.", "Push through the front heel to return; alternate legs."],
      mistakes: ["Front knee shooting past the toes.", "Leaning the torso forward."],
      easier: "Hold a wall for balance.", harder: "Add dumbbells.",
    },
  },
  {
    id: "glute-bridge", name: "Glute Bridge", emoji: "🌉", type: "strength",
    focus: ["legs", "core", "full"], muscles: ["glutes", "hamstrings", "core"],
    muscleLabel: "Glutes · Hamstrings", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "15 reps", defaultRest: 30,
    tip: "Lie on your back, drive your hips up, squeeze your glutes at the top.",
    howTo: {
      setup: "Lie on your back, knees bent, feet flat and hip-width, arms by your sides.",
      steps: ["Press through your heels and lift your hips toward the ceiling.", "Squeeze your glutes hard at the top.", "Lower with control."],
      mistakes: ["Over-arching the lower back — squeeze glutes, not back.", "Pushing through the toes."],
      easier: "Smaller lift.", harder: "Pause 2s at the top or do single-leg.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "rdl-dumbbell", name: "Dumbbell Romanian Deadlift", emoji: "🏋️‍♀️", type: "strength",
    focus: ["legs", "full"], muscles: ["hamstrings", "glutes", "back"],
    muscleLabel: "Hamstrings · Glutes", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 45,
    tip: "Hinge at the hips, dumbbells sliding down your thighs, flat back.",
    howTo: {
      setup: "Hold a dumbbell in each hand in front of your thighs, feet hip-width, knees soft.",
      steps: ["Push your hips back, lowering the weights along your legs.", "Stop when you feel a stretch in your hamstrings (about shin level).", "Drive hips forward to stand tall."],
      mistakes: ["Rounding the back — keep it flat.", "Turning it into a squat."],
      easier: "Lighter weight, smaller range.", harder: "Slow the lowering to 3s.",
    },
  },
  {
    id: "calf-raise", name: "Calf Raise", emoji: "🦶", type: "strength",
    focus: ["legs"], muscles: ["calves"],
    muscleLabel: "Calves", equipment: ["bodyweight", "dumbbell"], loaded: false,
    defaultSets: 3, defaultReps: "15 reps", defaultRest: 30,
    tip: "Rise onto the balls of your feet, pause, lower slowly.",
    howTo: {
      setup: "Stand tall near a wall for balance, feet hip-width.",
      steps: ["Push through the balls of your feet and lift your heels high.", "Pause at the top.", "Lower slowly until heels nearly touch the floor."],
      mistakes: ["Bouncing through reps.", "Rolling onto the outside of the foot."],
      easier: "Hold the wall.", harder: "Hold dumbbells or do one leg at a time.",
    },
  },
  {
    id: "wall-sit", name: "Wall Sit", emoji: "🧱", type: "strength",
    focus: ["legs", "core"], muscles: ["quads", "glutes"],
    muscleLabel: "Quads · Endurance", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "30 seconds", defaultRest: 30, defaultDuration: 30,
    tip: "Back against the wall, slide down to a 90° sit, hold.",
    howTo: {
      setup: "Stand with your back flat against a wall, feet about two feet out.",
      steps: ["Slide down until your thighs are parallel to the floor.", "Knees stacked over ankles at 90°.", "Hold, breathing steadily."],
      mistakes: ["Knees past the toes.", "Putting hands on the thighs for help."],
      easier: "Don't sit as low.", harder: "Lower deeper or extend the hold.",
    },
    excludedBy: ["knee-friendly"],
  },
  {
    id: "banded-squat", name: "Banded Squat", emoji: "🔵", type: "strength",
    focus: ["legs", "full"], muscles: ["quads", "glutes"],
    muscleLabel: "Quads · Glutes", equipment: ["bands"], loaded: false,
    defaultSets: 3, defaultReps: "15 reps", defaultRest: 30,
    tip: "Loop a band above your knees and squat, pushing knees out against it.",
    howTo: {
      setup: "Place a loop band just above your knees, feet shoulder-width.",
      steps: ["Push your knees out against the band.", "Sit back into a squat, keeping tension on the band.", "Drive up through your heels."],
      mistakes: ["Letting the band pull your knees inward.", "Shallow depth."],
      easier: "Lighter band.", harder: "Pause at the bottom.",
    },
  },
  {
    id: "step-up", name: "Step-Up", emoji: "🪜", type: "strength",
    focus: ["legs", "full", "cardio"], muscles: ["quads", "glutes"],
    muscleLabel: "Quads · Glutes", equipment: ["bodyweight", "dumbbell"], loaded: false,
    defaultSets: 3, defaultReps: "10 each side", defaultRest: 40,
    tip: "Step onto a sturdy bench/box, drive through the top leg.",
    howTo: {
      setup: "Stand facing a knee-height sturdy bench or step.",
      steps: ["Place one whole foot on the step.", "Drive through that heel to stand up on top.", "Step back down with control; alternate legs."],
      mistakes: ["Pushing off the bottom foot instead of the top leg.", "Using an unstable surface."],
      easier: "Use a lower step.", harder: "Hold dumbbells.",
    },
    excludedBy: ["knee-friendly"],
  },

  // ============================== ARMS / UPPER ==============================
  {
    id: "db-curl", name: "Dumbbell Biceps Curl", emoji: "💪", type: "strength",
    focus: ["arms", "full"], muscles: ["biceps"],
    muscleLabel: "Biceps", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 30,
    tip: "Elbows pinned to your sides, curl up, lower slowly.",
    howTo: {
      setup: "Stand tall, a dumbbell in each hand, palms facing forward.",
      steps: ["Keeping elbows glued to your sides, curl the weights up.", "Squeeze your biceps at the top.", "Lower slowly to full extension."],
      mistakes: ["Swinging the body to lift.", "Elbows drifting forward."],
      easier: "Lighter weight or one arm at a time.", harder: "3s lowering tempo.",
    },
  },
  {
    id: "hammer-curl", name: "Hammer Curl", emoji: "🔨", type: "strength",
    focus: ["arms", "full"], muscles: ["biceps"],
    muscleLabel: "Biceps · Forearms", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 30,
    tip: "Same as a curl but palms face each other the whole time.",
    howTo: {
      setup: "Dumbbell in each hand, palms facing your body (thumbs up).",
      steps: ["Curl the weights up keeping palms facing inward.", "Squeeze at the top.", "Lower with control."],
      mistakes: ["Rotating the wrists.", "Using momentum."],
      easier: "Lighter weight.", harder: "Alternate slow single arms.",
    },
  },
  {
    id: "triceps-kickback", name: "Triceps Kickback", emoji: "🦵", type: "strength",
    focus: ["arms"], muscles: ["triceps"],
    muscleLabel: "Triceps", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 30,
    tip: "Hinge forward, upper arm still, extend the weight straight back.",
    howTo: {
      setup: "Hinge at the hips ~45°, a dumbbell in each hand, upper arms tucked to your sides.",
      steps: ["Keeping upper arms still, straighten your elbows to press the weights back.", "Squeeze your triceps.", "Return to 90° with control."],
      mistakes: ["Moving the upper arm.", "Rounding the back."],
      easier: "Lighter weight, one arm.", harder: "Pause at full extension.",
    },
  },
  {
    id: "overhead-press", name: "Dumbbell Shoulder Press", emoji: "⬆️", type: "strength",
    focus: ["arms", "full"], muscles: ["shoulders", "triceps"],
    muscleLabel: "Shoulders · Triceps", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "10 reps", defaultRest: 45,
    tip: "Start at ear level, press overhead without arching your back.",
    howTo: {
      setup: "Sit or stand tall, dumbbells at ear height, palms forward.",
      steps: ["Brace your core.", "Press the dumbbells straight overhead until arms are extended.", "Lower back to ear level with control."],
      mistakes: ["Arching the lower back.", "Flaring elbows too far back."],
      easier: "Lighter weight or one arm.", harder: "Slow the lowering.",
    },
    excludedBy: ["shoulder-friendly"],
  },
  {
    id: "lateral-raise", name: "Lateral Raise", emoji: "🦅", type: "strength",
    focus: ["arms"], muscles: ["shoulders"],
    muscleLabel: "Shoulders", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 30,
    tip: "Raise the dumbbells out to the sides to shoulder height, soft elbows.",
    howTo: {
      setup: "Stand tall, a light dumbbell in each hand at your sides, slight elbow bend.",
      steps: ["Lift the weights out to the sides until arms are parallel to the floor.", "Lead with your elbows, pinkies slightly up.", "Lower slowly."],
      mistakes: ["Going too heavy and shrugging.", "Raising above shoulder height."],
      easier: "Very light weight.", harder: "Pause at the top.",
    },
    excludedBy: ["shoulder-friendly"],
  },
  {
    id: "pushup", name: "Push-Up", emoji: "🫷", type: "strength",
    focus: ["arms", "full", "core"], muscles: ["chest", "triceps", "shoulders", "core"],
    muscleLabel: "Chest · Triceps · Core", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "10 reps", defaultRest: 40,
    tip: "Body straight as a plank, lower your chest, press back up.",
    howTo: {
      setup: "Hands slightly wider than shoulders, body in a straight line from head to heels.",
      steps: ["Bend your elbows to lower your chest toward the floor.", "Keep elbows at ~45° from your body.", "Press back up to full arm extension."],
      mistakes: ["Hips sagging or piking up.", "Flaring elbows straight out."],
      easier: "Drop to your knees or push up from a wall/bench.", harder: "Slow 3s lowering.",
    },
  },
  {
    id: "chair-dip", name: "Chair Triceps Dip", emoji: "🪑", type: "strength",
    focus: ["arms"], muscles: ["triceps", "shoulders"],
    muscleLabel: "Triceps · Shoulders", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "10 reps", defaultRest: 40,
    tip: "Hands on a sturdy chair edge, bend elbows to dip, press up.",
    howTo: {
      setup: "Sit on the edge of a sturdy chair, hands gripping the edge beside your hips, feet out front.",
      steps: ["Slide your hips off the edge.", "Bend your elbows straight back to lower your hips.", "Press through your palms to rise."],
      mistakes: ["Elbows flaring out.", "Shrugging shoulders to the ears."],
      easier: "Bend knees closer to you.", harder: "Walk feet further out / straighten legs.",
    },
    excludedBy: ["shoulder-friendly"],
  },
  {
    id: "band-pull-apart", name: "Band Pull-Apart", emoji: "🎗️", type: "strength",
    focus: ["arms", "full"], muscles: ["back", "shoulders"],
    muscleLabel: "Upper Back · Rear Delts", equipment: ["bands"], loaded: false,
    defaultSets: 3, defaultReps: "15 reps", defaultRest: 30,
    tip: "Hold a band at shoulder height, pull it apart, squeeze shoulder blades.",
    howTo: {
      setup: "Hold a resistance band with both hands at shoulder height, arms extended forward.",
      steps: ["Pull the band apart by squeezing your shoulder blades together.", "Bring the band toward your chest.", "Return slowly with control."],
      mistakes: ["Shrugging the shoulders.", "Bending the elbows."],
      easier: "Wider grip (less tension).", harder: "Narrow grip or stronger band.",
    },
  },

  // ============================== BACK (full-body) ==============================
  {
    id: "db-row", name: "Dumbbell Row", emoji: "🚣", type: "strength",
    focus: ["full", "arms"], muscles: ["back", "biceps"],
    muscleLabel: "Back · Biceps", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "10 each side", defaultRest: 40,
    tip: "Hinge forward, pull the dumbbell to your hip, squeeze your back.",
    howTo: {
      setup: "Place one knee and hand on a bench, other foot on floor, dumbbell hanging from the free hand.",
      steps: ["Pull the dumbbell up toward your hip, leading with your elbow.", "Squeeze your shoulder blade at the top.", "Lower slowly; switch sides."],
      mistakes: ["Rotating the torso to yank the weight.", "Pulling to the chest instead of the hip."],
      easier: "Lighter weight.", harder: "Pause at the top for 1s.",
    },
  },
  {
    id: "band-row", name: "Resistance Band Row", emoji: "🔗", type: "strength",
    focus: ["full", "arms"], muscles: ["back", "biceps", "core"],
    muscleLabel: "Back · Biceps · Core", equipment: ["bands"], loaded: false,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 30,
    tip: "Anchor a band at chest height, sit tall, pull to your belly button.",
    howTo: {
      setup: "Anchor a band at chest height (or loop around your feet while seated), holding an end in each hand.",
      steps: ["Sit or stand tall with arms extended.", "Pull the handles to your belly button, elbows close to your sides.", "Squeeze your back, then return slowly."],
      mistakes: ["Leaning back to pull.", "Letting the shoulders shrug up."],
      easier: "Step closer to the anchor.", harder: "Step back for more tension.",
    },
  },
  {
    id: "db-chest-press", name: "Dumbbell Chest Press", emoji: "🛏️", type: "strength",
    focus: ["full", "arms"], muscles: ["chest", "triceps", "shoulders"],
    muscleLabel: "Chest · Triceps", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 45,
    tip: "On a bench or floor, dumbbells at chest level, press up and together.",
    howTo: {
      setup: "Lie on a bench (or the floor) holding a dumbbell in each hand at chest level, elbows at ~45°.",
      steps: ["Press the dumbbells up until your arms are extended.", "Bring them slightly together at the top.", "Lower with control to chest level."],
      mistakes: ["Flaring elbows straight out to 90°.", "Bouncing the weights."],
      easier: "Lighter weight, floor press (shorter range).", harder: "Slow 3s lowering.",
    },
  },
  {
    id: "reverse-fly", name: "Reverse Fly", emoji: "🦋", type: "strength",
    focus: ["full", "arms"], muscles: ["back", "shoulders"],
    muscleLabel: "Upper Back · Rear Delts", equipment: ["dumbbell"], loaded: true,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 30,
    tip: "Hinge forward, raise light dumbbells out to the sides like wings.",
    howTo: {
      setup: "Hinge forward ~45° with a flat back, light dumbbells hanging beneath you, palms facing each other.",
      steps: ["Raise the weights out to the sides, squeezing your shoulder blades.", "Stop at shoulder height.", "Lower slowly."],
      mistakes: ["Using momentum.", "Rounding the back."],
      easier: "Very light weight.", harder: "Pause at the top.",
    },
  },

  // ============================== CORE ==============================
  {
    id: "plank", name: "Plank Hold", emoji: "🧱", type: "strength",
    focus: ["core", "full"], muscles: ["core", "shoulders"],
    muscleLabel: "Core · Shoulders", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "30 seconds", defaultRest: 30, defaultDuration: 30,
    tip: "Forearms down, body straight as a board. Breathe steadily.",
    howTo: {
      setup: "Forearms on the floor under your shoulders, legs extended behind you on your toes.",
      steps: ["Lift your hips so your body forms a straight line.", "Brace your abs and squeeze your glutes.", "Hold, breathing steadily."],
      mistakes: ["Hips sagging or piking up.", "Holding your breath."],
      easier: "Drop to your knees.", harder: "Extend the hold or lift one foot.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "dead-bug", name: "Dead Bug", emoji: "🐛", type: "strength",
    focus: ["core"], muscles: ["core"],
    muscleLabel: "Deep Core", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "10 each side", defaultRest: 30,
    tip: "On your back, lower opposite arm and leg, keep your low back flat.",
    howTo: {
      setup: "Lie on your back, arms reaching toward the ceiling, knees bent at 90° over your hips.",
      steps: ["Slowly lower one arm overhead and the opposite leg toward the floor.", "Keep your lower back pressed flat.", "Return and switch sides."],
      mistakes: ["Letting the lower back arch off the floor.", "Moving too fast."],
      easier: "Move just the legs.", harder: "Lower limbs closer to the floor.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "bird-dog", name: "Bird Dog", emoji: "🐕", type: "strength",
    focus: ["core", "full"], muscles: ["core", "back"],
    muscleLabel: "Core · Lower Back", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "10 each side", defaultRest: 30,
    tip: "On all fours, extend opposite arm and leg, stay level.",
    howTo: {
      setup: "On hands and knees, wrists under shoulders, knees under hips.",
      steps: ["Extend one arm forward and the opposite leg back.", "Keep your hips and shoulders square to the floor.", "Return with control and switch sides."],
      mistakes: ["Twisting the hips.", "Arching the back."],
      easier: "Extend just an arm or just a leg.", harder: "Pause 2s at full extension.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "bicycle-crunch", name: "Bicycle Crunch", emoji: "🚲", type: "strength",
    focus: ["core"], muscles: ["core"],
    muscleLabel: "Abs · Obliques", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "20 reps", defaultRest: 30,
    tip: "Bring opposite elbow to knee, pedaling slowly with control.",
    howTo: {
      setup: "Lie on your back, hands lightly behind your head, knees lifted.",
      steps: ["Bring one knee in while rotating the opposite elbow toward it.", "Extend the other leg out.", "Alternate in a slow pedaling motion."],
      mistakes: ["Yanking on the neck.", "Rushing through reps."],
      easier: "Keep feet higher / slower pace.", harder: "Extend legs lower.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "side-plank", name: "Side Plank", emoji: "📐", type: "strength",
    focus: ["core"], muscles: ["core"],
    muscleLabel: "Obliques", equipment: ["bodyweight"], loaded: false,
    defaultSets: 2, defaultReps: "20s each side", defaultRest: 30, defaultDuration: 20,
    tip: "On one forearm, stack your body, lift your hips, hold.",
    howTo: {
      setup: "Lie on your side, forearm under your shoulder, legs stacked.",
      steps: ["Lift your hips so your body is a straight diagonal line.", "Hold, keeping your neck neutral.", "Switch sides halfway."],
      mistakes: ["Hips sagging toward the floor.", "Rotating forward."],
      easier: "Bottom knee on the floor.", harder: "Lift the top leg.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "russian-twist", name: "Russian Twist", emoji: "🌀", type: "strength",
    focus: ["core"], muscles: ["core"],
    muscleLabel: "Obliques", equipment: ["bodyweight", "dumbbell"], loaded: false,
    defaultSets: 3, defaultReps: "16 reps", defaultRest: 30,
    tip: "Lean back, feet up, rotate side to side with control.",
    howTo: {
      setup: "Sit with knees bent, lean back ~45°, feet hovering (or heels down to start).",
      steps: ["Clasp your hands (or hold a weight) at your chest.", "Rotate your torso to tap toward one hip, then the other.", "Keep your chest tall throughout."],
      mistakes: ["Rounding the back.", "Just moving the arms, not the torso."],
      easier: "Keep heels on the floor.", harder: "Hold a dumbbell and lift the feet.",
    },
    excludedBy: ["no-floor"],
  },

  // ============================== CARDIO ==============================
  {
    id: "high-knees", name: "High Knees", emoji: "🏃", type: "cardio",
    focus: ["cardio", "full", "core"], muscles: ["cardio", "core"],
    muscleLabel: "Heart Rate · Core", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "30 seconds", defaultRest: 30, defaultDuration: 30,
    tip: "Run in place driving your knees up to hip height, fast arms.",
    howTo: {
      setup: "Stand tall in a clear space, arms bent.",
      steps: ["Drive your knees up toward hip height alternately, fast.", "Stay on the balls of your feet.", "Pump your arms to match."],
      mistakes: ["Leaning back.", "Low knees — aim for hip height."],
      easier: "Slow it to a march.", harder: "Increase speed.",
    },
    excludedBy: ["no-jumping", "quiet", "knee-friendly"],
  },
  {
    id: "mountain-climber", name: "Mountain Climbers", emoji: "⛰️", type: "cardio",
    focus: ["cardio", "core", "full"], muscles: ["cardio", "core", "shoulders"],
    muscleLabel: "Core · Heart Rate", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "30 seconds", defaultRest: 30, defaultDuration: 30,
    tip: "In a plank, drive your knees toward your chest one at a time.",
    howTo: {
      setup: "Start in a high plank, hands under shoulders, body straight.",
      steps: ["Drive one knee toward your chest.", "Quickly switch legs in a running motion.", "Keep your hips low and level."],
      mistakes: ["Hips bouncing high.", "Hands creeping forward."],
      easier: "Slow, controlled steps.", harder: "Speed up.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "butt-kicks", name: "Butt Kicks", emoji: "🦵", type: "cardio",
    focus: ["cardio", "legs"], muscles: ["cardio", "hamstrings"],
    muscleLabel: "Heart Rate · Hamstrings", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "30 seconds", defaultRest: 30, defaultDuration: 30,
    tip: "Jog in place flicking your heels up toward your glutes.",
    howTo: {
      setup: "Stand tall, arms bent.",
      steps: ["Jog in place, kicking your heels up toward your glutes.", "Stay light on the balls of your feet.", "Keep a quick rhythm."],
      mistakes: ["Leaning forward.", "Slamming the feet down."],
      easier: "Slow the pace.", harder: "Quicken and lift heels higher.",
    },
    excludedBy: ["quiet", "knee-friendly"],
  },
  {
    id: "squat-to-press", name: "Squat to Press", emoji: "🏗️", type: "cardio",
    focus: ["cardio", "full", "legs"], muscles: ["fullbody", "shoulders", "quads"],
    muscleLabel: "Full Body Burner", equipment: ["bodyweight", "dumbbell"], loaded: false,
    defaultSets: 3, defaultReps: "12 reps", defaultRest: 40,
    tip: "Squat down, then stand and press your arms (or weights) overhead.",
    howTo: {
      setup: "Stand shoulder-width, hands at your shoulders (or dumbbells at shoulder height).",
      steps: ["Lower into a squat.", "Drive up powerfully through your heels.", "As you stand, press your hands/weights overhead.", "Return for the next rep."],
      mistakes: ["Pressing before fully standing.", "Arching the back at the top."],
      easier: "Bodyweight, smaller squat.", harder: "Add dumbbells.",
    },
  },
  {
    id: "skater-hops", name: "Skater Hops", emoji: "⛸️", type: "cardio",
    focus: ["cardio", "legs"], muscles: ["cardio", "glutes", "quads"],
    muscleLabel: "Heart Rate · Legs", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "30 seconds", defaultRest: 30, defaultDuration: 30,
    tip: "Bound side to side, landing softly on one leg like a speed skater.",
    howTo: {
      setup: "Stand on one leg, knee slightly bent.",
      steps: ["Push off sideways and land softly on the other foot.", "Let the trailing leg sweep behind you.", "Bound back and forth with control."],
      mistakes: ["Landing stiff-legged.", "Losing balance from going too wide."],
      easier: "Step side to side, no hop.", harder: "Bigger, faster bounds.",
    },
    excludedBy: ["no-jumping", "quiet", "knee-friendly"],
  },
  {
    id: "shadow-box", name: "Shadow Boxing", emoji: "🥊", type: "cardio",
    focus: ["cardio", "arms", "core"], muscles: ["cardio", "shoulders", "core"],
    muscleLabel: "Heart Rate · Shoulders", equipment: ["bodyweight"], loaded: false,
    defaultSets: 3, defaultReps: "45 seconds", defaultRest: 30, defaultDuration: 45,
    tip: "Light on your feet, throw controlled punches, keep your core tight.",
    howTo: {
      setup: "Feet staggered, hands up by your chin, knees soft.",
      steps: ["Throw alternating jabs and crosses with controlled power.", "Rotate through your torso, not just the arms.", "Keep bouncing lightly on your feet."],
      mistakes: ["Locking the elbows on punches.", "Dropping your hands."],
      easier: "Slower punches, no bounce.", harder: "Add hooks and speed.",
    },
  },

  // ============================== COOLDOWNS ==============================
  {
    id: "quad-stretch", name: "Standing Quad Stretch", emoji: "🦵", type: "cooldown",
    focus: ["full", "legs", "cardio", "core", "arms"], muscles: ["mobility", "quads"],
    muscleLabel: "Quads", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30s each side", defaultRest: 0, defaultDuration: 30,
    tip: "Hold your foot behind you, stand tall, feel the front of your thigh.",
    howTo: {
      setup: "Stand tall, hold a wall for balance if needed.",
      steps: ["Bend one knee and grab that foot behind you.", "Gently pull your heel toward your glute.", "Keep your knees together; switch sides."],
      mistakes: ["Arching the back.", "Letting the knee splay out."],
      easier: "Use a strap/towel around the foot.", harder: "Hold longer, deeper.",
    },
  },
  {
    id: "hamstring-stretch", name: "Seated Hamstring Stretch", emoji: "🧘", type: "cooldown",
    focus: ["full", "legs", "cardio", "core"], muscles: ["mobility", "hamstrings"],
    muscleLabel: "Hamstrings", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Sit, reach for your toes, hold gently — no bouncing.",
    howTo: {
      setup: "Sit on the floor with legs extended in front of you.",
      steps: ["Hinge at the hips and reach toward your toes.", "Go to a gentle stretch, not pain.", "Breathe and hold; relax deeper on exhales."],
      mistakes: ["Bouncing to go further.", "Rounding hard through the neck."],
      easier: "Bend the knees slightly.", harder: "Reach past the toes.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "chest-opener", name: "Chest Opener Stretch", emoji: "🫸", type: "cooldown",
    focus: ["full", "arms", "core", "cardio"], muscles: ["mobility", "chest", "shoulders"],
    muscleLabel: "Chest · Shoulders", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30 seconds", defaultRest: 0, defaultDuration: 30,
    tip: "Clasp your hands behind your back, open your chest toward the ceiling.",
    howTo: {
      setup: "Stand tall, clasp your hands together behind your back.",
      steps: ["Straighten your arms and lift your hands slightly.", "Open your chest and squeeze your shoulder blades.", "Hold and breathe."],
      mistakes: ["Shrugging shoulders up.", "Leaning forward."],
      easier: "Hold a towel between your hands.", harder: "Lift the hands higher.",
    },
  },
  {
    id: "childs-pose", name: "Child's Pose", emoji: "🧎", type: "cooldown",
    focus: ["full", "core", "legs", "arms", "cardio"], muscles: ["mobility", "back"],
    muscleLabel: "Back · Hips", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "40 seconds", defaultRest: 0, defaultDuration: 40,
    tip: "Kneel and reach forward, melt your chest toward the floor.",
    howTo: {
      setup: "Kneel on the floor, big toes together, knees apart.",
      steps: ["Sit your hips back toward your heels.", "Reach your arms forward and lower your chest.", "Rest your forehead down and breathe slowly."],
      mistakes: ["Holding tension in the shoulders.", "Forcing the hips down."],
      easier: "Place a cushion under your hips.", harder: "Walk hands further forward.",
    },
    excludedBy: ["no-floor", "knee-friendly"],
  },
  {
    id: "figure-four", name: "Figure-4 Glute Stretch", emoji: "4️⃣", type: "cooldown",
    focus: ["full", "legs", "cardio", "core"], muscles: ["mobility", "glutes"],
    muscleLabel: "Glutes · Hips", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30s each side", defaultRest: 0, defaultDuration: 30,
    tip: "Lie down, cross one ankle over the opposite knee, pull the thigh in.",
    howTo: {
      setup: "Lie on your back, knees bent, feet flat.",
      steps: ["Cross one ankle over the opposite thigh, making a '4'.", "Reach through and pull the bottom thigh toward your chest.", "Feel the stretch in the glute; switch sides."],
      mistakes: ["Lifting the head and straining the neck.", "Pulling into pain."],
      easier: "Keep the bottom foot on the floor.", harder: "Pull the thigh closer.",
    },
    excludedBy: ["no-floor"],
  },
  {
    id: "shoulder-stretch", name: "Cross-Body Shoulder Stretch", emoji: "💆", type: "cooldown",
    focus: ["full", "arms", "core", "cardio"], muscles: ["mobility", "shoulders"],
    muscleLabel: "Shoulders", equipment: ["bodyweight"], loaded: false,
    defaultSets: 1, defaultReps: "30s each side", defaultRest: 0, defaultDuration: 30,
    tip: "Pull one straight arm across your chest with the other hand.",
    howTo: {
      setup: "Stand or sit tall.",
      steps: ["Bring one arm straight across your chest.", "Use the other hand to gently pull it closer.", "Hold, then switch arms."],
      mistakes: ["Shrugging the stretched shoulder.", "Bending the arm."],
      easier: "Lighter pull.", harder: "Hold a touch longer.",
    },
  },
];

export const EXERCISE_MAP: Record<string, Exercise> = Object.fromEntries(
  EXERCISES.map((e) => [e.id, e])
);

export function getExercise(id: string): Exercise | undefined {
  return EXERCISE_MAP[id];
}
