import type { Exercise } from "./types";

// The ~30 moves for "The Block," transcribed from Justin's coach's
// spreadsheet. Cues and the "See how it's done" video links come verbatim from
// the source cells/hyperlinks; how-to copy is authored to match. Curated
// equipment substitutions follow PRD §5 (progression still tracks under the
// original id, so a swap never splits a lift's history).

export const EXERCISES: Exercise[] = [
  // ============================ SHARED WARM-UP ============================
  {
    id: "yogi-squat-fold",
    name: "Yogi Squat to Forward Fold",
    emoji: "🧘",
    type: "warmup",
    setType: "reps",
    loaded: false,
    equipment: ["bodyweight"],
    cue: "Move with your breath, sink into the squat and lengthen on the fold.",
    videoUrl: "https://www.youtube.com/watch?v=EBbWYMg3nic",
    howTo: {
      setup: "Stand with feet a little wider than hips, toes turned slightly out.",
      steps: [
        "Sink into a deep squat, elbows inside the knees, chest tall.",
        "Press the knees gently open and breathe into the hips.",
        "Straighten the legs into a forward fold, letting the head hang.",
        "Re-bend the knees to return to the squat. That's one rep.",
      ],
      mistakes: ["Rounding hard through the low back", "Rushing — this is a mobility move, not a rep chase"],
      easier: "Hold a doorframe or TRX for balance and reduce depth.",
      harder: "Pause 2–3 breaths at the bottom of each squat.",
    },
  },
  {
    id: "downward-dog-plank",
    name: "Downward Dog to High Plank",
    emoji: "🐕",
    type: "warmup",
    setType: "reps",
    loaded: false,
    equipment: ["bodyweight"],
    cue: "Flow smoothly between the two shapes, long spine throughout.",
    videoUrl: "https://youtu.be/u8eUdDxyAMg?feature=shared",
    howTo: {
      setup: "Start on hands and knees, hands under shoulders.",
      steps: [
        "Press back and up into downward dog, hips high, heels reaching down.",
        "Shift forward into a high plank, shoulders stacked over wrists.",
        "Press back up to downward dog. That's one rep.",
      ],
      mistakes: ["Letting the hips sag in plank", "Bunching the shoulders up by the ears"],
      easier: "Drop to the knees in the plank position.",
      harder: "Add a shoulder tap at the top of each plank.",
    },
  },
  {
    id: "band-pull-aparts",
    name: "Band Pull Aparts",
    emoji: "🎯",
    type: "warmup",
    setType: "reps",
    loaded: false,
    equipment: ["bands"],
    cue: "Squeeze the shoulder blades, keep the ribs down.",
    videoUrl: "https://youtu.be/Zshy9ODExCc?feature=shared",
    howTo: {
      setup: "Hold a light band at shoulder height, arms straight in front, palms down.",
      steps: [
        "Pull the band apart by driving the hands out to the sides.",
        "Squeeze the shoulder blades together at the end range.",
        "Control the band back to the start. That's one rep.",
      ],
      mistakes: ["Shrugging the shoulders up", "Bending the elbows to cheat the range"],
      easier: "Choke up on the band for less tension.",
      harder: "Pause for a beat at full stretch.",
    },
  },
  {
    id: "worlds-greatest",
    name: "World's Greatest Stretch",
    emoji: "🌍",
    type: "warmup",
    setType: "reps-perside",
    loaded: false,
    equipment: ["bodyweight"],
    cue: "Open through the front hip and rotate the chest to the sky.",
    videoUrl: "https://youtu.be/FIZMUyAPPWY?feature=shared",
    howTo: {
      setup: "Start in a high plank.",
      steps: [
        "Step the right foot up outside the right hand into a lunge.",
        "Drop the right elbow toward the floor, then rotate and reach that arm to the ceiling.",
        "Return the hand down, step back to plank, switch sides.",
      ],
      mistakes: ["Letting the back hip collapse", "Forcing the rotation past comfortable range"],
      easier: "Drop the back knee to the floor.",
      harder: "Add a gentle thoracic rotation pause at the top of each reach.",
    },
  },
  {
    id: "ninety-ninety-hip-lift",
    name: "90/90 Hip Lift with Reach",
    emoji: "🦵",
    type: "warmup",
    setType: "reps-perside",
    loaded: false,
    equipment: ["bodyweight"],
    // NOTE: source spreadsheet left reps blank — treated as a quality/feel move,
    // default 5 each side. One-line change here if the coach specifies a count.
    cue: "A quality/feel move — lift the hips and reach long, no rushing.",
    videoUrl: "https://youtu.be/bWf5zEeMQEI?si=KUMqscLGx7j0TwEj",
    howTo: {
      setup: "Sit with both knees bent at 90°, one leg in front and one out to the side.",
      steps: [
        "From the 90/90 position, lift the hips off the floor toward the front knee.",
        "Reach the opposite arm long overhead as the hips rise.",
        "Lower with control and reset. Repeat, then switch sides.",
      ],
      mistakes: ["Cranking through the low back instead of the hips", "Holding the breath"],
      easier: "Reduce the height of the hip lift.",
      harder: "Pause at the top and add the reach for a longer count.",
    },
  },
  {
    id: "foam-roller-flow",
    name: "Foam Roller Flow",
    emoji: "🧻",
    type: "warmup",
    setType: "timed",
    loaded: false,
    equipment: ["full"],
    cue: "30 sec each: quads, hamstrings, IT band, back. Slow, breathe, ease off knots.",
    videoLinks: [
      { label: "Quads", url: "https://youtu.be/1XzS9y-vJD8" },
      { label: "Hamstrings", url: "https://www.youtube.com/shorts/FK6jYoQtGiI?feature=share" },
      { label: "IT Band", url: "https://youtu.be/eI9qLfSlCuI?feature=shared" },
      { label: "Back", url: "https://youtu.be/Orfqe-CQIZo?feature=shared" },
    ],
    howTo: {
      setup: "Have the foam roller and a clear patch of floor.",
      steps: [
        "Quads: face down, roller under the thighs, roll hip-to-knee for 30 sec.",
        "Hamstrings: seated, roller under the backs of the thighs, 30 sec.",
        "IT band: on your side, roller along the outer thigh, 30 sec each side.",
        "Back: roller under the upper back, support the head, roll the mid-back 30 sec.",
      ],
      mistakes: ["Rolling directly on a joint or the low back", "Holding your breath on a tender spot"],
      easier: "Use a softer roller or carry less of your weight onto it.",
      harder: "Pause and breathe on the tightest spots for 5–10 seconds.",
    },
  },

  // ============================ DAY 1 ============================
  {
    id: "quick-ropes",
    name: "Quick Ropes",
    emoji: "🪢",
    type: "cardio",
    setType: "timed",
    loaded: false,
    equipment: ["full"],
    cue: "Quick pace, core engaged.",
    videoUrl: "https://youtu.be/zw0OMi00X5g?si=BuuSoxXY2epTI1sp&t=25",
    howTo: {
      setup: "Grab the rope, a touch of space around you.",
      steps: ["Stay light on the balls of the feet.", "Keep a quick, steady cadence.", "Brace the core and breathe in rhythm."],
      mistakes: ["Going too high on the jumps", "Letting the pace sag late in the interval"],
      easier: "Step instead of jump, or shorten the interval.",
      harder: "Pick up the cadence in the final 10 seconds.",
    },
  },
  {
    id: "row-machine-sprints",
    name: "Row Machine Sprints",
    emoji: "🚣",
    type: "cardio",
    setType: "timed",
    loaded: false,
    equipment: ["full"],
    cue: "Quick pace, core engaged.",
    videoUrl: "https://youtu.be/2gm8tiSp23c?si=Hzt2AT_XOSjF3gOR&t=67",
    howTo: {
      setup: "Strap in, set the damper to a moderate setting.",
      steps: ["Drive with the legs first, then swing the back, then pull the arms.", "Return arms-back-legs in order.", "Keep the strokes powerful and rhythmic."],
      mistakes: ["Yanking with the arms early", "Rounding the back on the drive"],
      easier: "Lower the stroke rate, keep the form crisp.",
      harder: "Hold a stronger pace for the full interval.",
    },
  },
  {
    id: "incline-db-bench",
    name: "Incline DB Bench Press",
    emoji: "🏋️",
    type: "strength",
    setType: "reps",
    loaded: true,
    equipment: ["dumbbell", "full"],
    cue: "Arms in line with chest, control up and down.",
    videoUrl: "https://youtu.be/oZVCBM9f8Eo?si=6tY11Z4X74so9MtQ",
    howTo: {
      setup: "Set the bench to a low incline, dumbbells at shoulder level.",
      steps: ["Press the dumbbells up until the arms are nearly straight.", "Keep the wrists stacked over the elbows.", "Lower under control until you feel a stretch across the chest."],
      mistakes: ["Flaring the elbows to 90°", "Bouncing the weights off the bottom"],
      easier: "Lighter dumbbells, slightly lower incline.",
      harder: "Add a 1-second pause at the bottom of each rep.",
    },
    subs: [
      { id: "flat-bench", label: "Flat DB / Barbell Bench", note: "Press on a flat bench if there's no incline available.", equipment: ["dumbbell"] },
    ],
  },
  {
    id: "leg-curl-machine",
    name: "Leg Curl Machine",
    emoji: "🦿",
    type: "strength",
    setType: "reps",
    loaded: true,
    equipment: ["full"],
    cue: "Toes up, feet flexed.",
    videoUrl: "https://www.youtube.com/shorts/xdbEG3xGLI8",
    howTo: {
      setup: "Adjust the pad to sit just above the heels; line the knees up with the pivot.",
      steps: ["Curl the heels toward the glutes.", "Squeeze the hamstrings at the top.", "Lower slowly to full stretch."],
      mistakes: ["Letting the hips pop off the pad", "Using momentum to fling the weight"],
      easier: "Lighter load, focus on the squeeze.",
      harder: "Slow the lowering phase to 3 seconds.",
    },
    subs: [
      { id: "slider-curl", label: "Slider / Swiss-ball Curls", note: "Same hamstring target, no machine — heels on sliders or a ball.", equipment: ["bodyweight"] },
    ],
  },
  {
    id: "chest-fly-machine",
    name: "Chest Fly Machine",
    emoji: "🦋",
    type: "strength",
    setType: "reps",
    loaded: true,
    equipment: ["full"],
    cue: "Keep shoulders away from ears.",
    videoUrl: "https://www.youtube.com/shorts/XZg28DIf1oc",
    howTo: {
      setup: "Set the seat so the handles sit at chest height; a soft bend in the elbows.",
      steps: ["Bring the handles together in front of the chest.", "Squeeze the chest at the midline.", "Open the arms slowly to a comfortable stretch."],
      mistakes: ["Shrugging the shoulders up", "Bending the elbows to turn it into a press"],
      easier: "Reduce the range on the stretch side.",
      harder: "Pause and squeeze for a beat at the midline.",
    },
    subs: [
      { id: "db-fly", label: "Dumbbell Flyes", note: "Flyes on a flat bench with dumbbells.", equipment: ["dumbbell"] },
      { id: "band-fly", label: "Banded Flyes", note: "Flyes from a pair of anchors with bands.", equipment: ["bands"] },
    ],
  },
  {
    id: "barbell-hip-thrusts",
    name: "Barbell Hip Thrusts",
    emoji: "🍑",
    type: "strength",
    setType: "reps",
    loaded: true,
    equipment: ["full"],
    cue: "Neutral spine, squeeze glutes at the top.",
    // No demo link in the source spreadsheet for this move.
    howTo: {
      setup: "Upper back against a bench, barbell (padded) across the hips, feet flat.",
      steps: ["Drive through the heels and lift the hips to full extension.", "Squeeze the glutes hard at the top, ribs down.", "Lower under control without dumping into the low back."],
      mistakes: ["Over-arching the low back at the top", "Pushing through the toes instead of the heels"],
      easier: "Bodyweight or a single dumbbell across the hips.",
      harder: "Pause 2 seconds at lockout each rep.",
    },
  },
  {
    id: "kb-around-worlds",
    name: "KB Around the Worlds",
    emoji: "🌐",
    type: "strength",
    setType: "reps-perside",
    loaded: true,
    equipment: ["dumbbell", "full"],
    cue: "Don't let the KB touch the body, brace the core.",
    videoUrl: "https://youtu.be/1jq_Bkch9SA?si=7YZOWJq-1vuF1J1S",
    howTo: {
      setup: "Stand tall holding a kettlebell, core braced.",
      steps: ["Pass the kettlebell around the head in a circle.", "Keep it just off the body the whole way.", "Complete the reps one direction, then reverse for the other side."],
      mistakes: ["Letting the bell bonk the head/shoulders", "Leaning the torso to follow the weight"],
      easier: "Lighter bell, smaller circle.",
      harder: "Slow the circle and keep the bell further from the body.",
    },
  },

  // ============================ DAY 2 ============================
  {
    id: "sled-push-pull",
    name: "Sled Push-to-Pull (down & back)",
    emoji: "🛷",
    type: "strength",
    setType: "rounds",
    loaded: true,
    equipment: ["full"],
    cue: "Let a single rope fall behind, then pull the sled back.",
    videoUrl: "https://youtu.be/fmH610150pE?si=Pd-iUhp14d2JJ1tI",
    howTo: {
      setup: "Load the sled, rope attached and coiled. Clear lane down and back.",
      steps: ["Push the sled the length of the lane, low and driving through the legs.", "Drop a rope behind you at the far end.", "Hand-over-hand pull the sled all the way back. That's one round."],
      mistakes: ["Standing too upright on the push", "Pulling with the arms only on the way back"],
      easier: "Strip a plate off; shorten the lane.",
      harder: "Add load or push for a longer lane.",
    },
    subs: [
      { id: "carries", label: "Heavy Farmer Carries", note: "Heavy carries down & back for the same time under load.", equipment: ["dumbbell", "full"] },
      { id: "tread-push", label: "Treadmill Push", note: "Push a motor-off treadmill belt down & back.", equipment: ["full"] },
    ],
  },
  {
    id: "slider-mountain-climbers",
    name: "Slider Mountain Climbers",
    emoji: "🏔️",
    type: "cardio",
    setType: "timed",
    loaded: false,
    equipment: ["bodyweight"],
    cue: "Keep hips down.",
    videoUrl: "https://youtu.be/BpnUBdclaFU?si=pbZvPNYVKaGQG4c1&t=19",
    howTo: {
      setup: "High plank with the balls of both feet on sliders (or towels on a smooth floor).",
      steps: ["Drive one knee toward the chest, sliding the foot in.", "Slide it back as the other knee drives in.", "Keep a quick, controlled rhythm."],
      mistakes: ["Letting the hips pike up", "Bouncing instead of sliding"],
      easier: "Slower tempo, or step the feet instead of sliding.",
      harder: "Pick up the cadence while keeping the hips level.",
    },
  },
  {
    id: "trx-inverted-row",
    name: "TRX Inverted Row",
    emoji: "🪂",
    type: "strength",
    setType: "reps",
    loaded: false,
    equipment: ["full"],
    cue: "Shoulders relaxed.",
    videoUrl: "https://www.youtube.com/shorts/S2D7vdfEDeg?feature=share",
    howTo: {
      setup: "Set the TRX mid-length, grab the handles, walk the feet forward to lean back.",
      steps: ["Hang with straight arms, body in a straight line.", "Pull the chest to the handles, elbows tracking back.", "Lower under control to full extension."],
      mistakes: ["Letting the hips sag", "Shrugging the shoulders to the ears"],
      easier: "Walk the feet back to make the body more upright.",
      harder: "Walk the feet forward — the more horizontal, the harder.",
    },
    subs: [
      { id: "bar-row", label: "Bar Inverted Row", note: "Inverted row under a fixed bar in a rack.", equipment: ["full"] },
      { id: "band-row", label: "Banded Row", note: "Seated or standing row from a band anchor.", equipment: ["bands"] },
    ],
  },
  {
    id: "sandbag-walking-lunges",
    name: "Sandbag Walking Lunges",
    emoji: "🎒",
    type: "strength",
    setType: "reps-perside",
    loaded: true,
    equipment: ["dumbbell", "full"],
    cue: "Push up through the front foot, evenly distributed.",
    videoUrl: "https://www.youtube.com/watch?v=MdbmUltyo5I",
    howTo: {
      setup: "Sandbag on the shoulders or in a front-hold, tall posture.",
      steps: ["Step forward into a lunge, both knees to ~90°.", "Drive through the front heel to stand.", "Step through into the next lunge, alternating legs."],
      mistakes: ["Letting the front knee cave inward", "Leaning the torso forward"],
      easier: "Bodyweight or lighter load; shorten the step.",
      harder: "Add load or pause at the bottom of each lunge.",
    },
  },
  {
    id: "straight-arm-lat-pulldown",
    name: "Straight-Arm Lat Pulldown",
    emoji: "🔻",
    type: "strength",
    setType: "reps",
    loaded: true,
    equipment: ["full"],
    cue: "Shoulders down, neck elongated.",
    videoUrl: "https://youtu.be/wcVDItawocI?si=-Sa7ONx30EUdeoVa",
    howTo: {
      setup: "Stand at a high cable with a straight bar, slight hinge, soft elbows.",
      steps: ["Keep the arms long and sweep the bar down to the thighs.", "Drive from the lats, not the triceps.", "Control the bar back up to a stretch."],
      mistakes: ["Bending the elbows into a triceps pushdown", "Rounding the upper back"],
      easier: "Lighter load, focus on feeling the lats.",
      harder: "Pause for a beat at the bottom with the lats squeezed.",
    },
  },
  {
    id: "heel-elevated-goblet-squats",
    name: "Heel-Elevated Goblet Squats",
    emoji: "🏺",
    type: "strength",
    setType: "reps",
    loaded: true,
    equipment: ["dumbbell", "full"],
    cue: "Weight in heels, tall chest, pause at the bottom then stand.",
    videoUrl: "https://www.youtube.com/watch?v=RUXLuZ_GLrE",
    howTo: {
      setup: "Heels on a small plate or wedge, hold a dumbbell/kettlebell at the chest.",
      steps: ["Sit straight down, knees tracking over the toes.", "Pause for a beat at the bottom, chest tall.", "Drive up through the whole foot to stand."],
      mistakes: ["Letting the chest collapse forward", "Bouncing out of the bottom"],
      easier: "Lighter load or reduce depth.",
      harder: "Add load or a longer pause at the bottom.",
    },
  },
  {
    id: "pallof-press-step-out",
    name: "Pallof Press + Step Out",
    emoji: "🧱",
    type: "strength",
    setType: "reps-perside",
    loaded: true,
    equipment: ["bands", "full"],
    cue: "Resist the pull, brace, step laterally out and control back.",
    videoUrl: "https://youtu.be/ma2OjgP5XDc?feature=shared",
    howTo: {
      setup: "Stand side-on to a cable/band anchor at chest height, hands at the sternum.",
      steps: ["Press the handle straight out, resisting the pull toward the anchor.", "Take a lateral step away from the anchor, staying braced.", "Step back and bring the hands in. That's one rep on that side."],
      mistakes: ["Letting the torso twist toward the anchor", "Holding the breath instead of bracing"],
      easier: "Reduce the band tension; skip the step.",
      harder: "Increase tension or take a longer step out.",
    },
  },

  // ============================ DAY 3 ============================
  {
    id: "assault-bike-sprints",
    name: "Assault Bike Sprints",
    emoji: "🚲",
    type: "cardio",
    setType: "timed",
    loaded: false,
    equipment: ["full"],
    cue: "Quick pace, core engaged.",
    videoUrl: "https://www.youtube.com/shorts/ZjcyZCLjxC0",
    howTo: {
      setup: "Set the seat height, grab the handles.",
      steps: ["Drive with arms and legs together.", "Hit a hard, steady pace for the interval.", "Keep breathing rhythmic, core braced."],
      mistakes: ["Starting too hot and fading", "Slumping over the handles"],
      easier: "Lower the target pace; shorten the sprint.",
      harder: "Hold a higher pace through the final seconds.",
    },
    subs: [
      { id: "row-erg", label: "Row Erg Sprints", note: "Same interval on a rowing erg.", equipment: ["full"] },
      { id: "jump-rope", label: "Jump Rope Intervals", note: "Same interval skipping rope.", equipment: ["bodyweight"] },
    ],
  },
  {
    id: "wall-sit",
    name: "Wall Sit",
    emoji: "🧱",
    type: "strength",
    setType: "timed",
    loaded: false,
    equipment: ["bodyweight"],
    cue: "Weight in heels, tall proud chest.",
    videoUrl: "https://youtu.be/y-wV4Venusw?si=KZ-Nk6G74Tm4bswY",
    howTo: {
      setup: "Back flat against a wall, walk the feet out, slide down to ~90° at the knees.",
      steps: ["Hold with thighs parallel to the floor.", "Weight in the heels, back flat on the wall.", "Breathe steadily and hold the time."],
      mistakes: ["Letting the hips creep up", "Knees drifting past the toes"],
      easier: "Sit a little higher than 90°.",
      harder: "Hold a plate on the thighs, or go single-leg for a few seconds.",
    },
  },
  {
    id: "alt-shoulder-raises",
    name: "Alt. Front/Lateral Shoulder Raises",
    emoji: "🙆",
    type: "strength",
    setType: "reps-perside",
    loaded: true,
    equipment: ["dumbbell", "full"],
    cue: "Slow and controlled.",
    videoUrl: "https://youtu.be/N0tTk_Y9vLw?si=9qSCiBVLC1mUO4kl",
    howTo: {
      setup: "A light dumbbell in each hand, standing tall, soft elbows.",
      steps: ["Raise one arm to the front to shoulder height.", "Lower, then raise the same arm out to the side.", "Lower with control and alternate arms."],
      mistakes: ["Swinging the weights up with momentum", "Shrugging the traps"],
      easier: "Lighter dumbbells; one plane at a time.",
      harder: "Slow the lowering and pause at the top.",
    },
  },
  {
    id: "slider-hamstring-curls",
    name: "Slider Hamstring Curls",
    emoji: "🛹",
    type: "strength",
    setType: "reps",
    loaded: false,
    equipment: ["bodyweight"],
    cue: "Toes up, heels digging in, hips up.",
    videoUrl: "https://www.youtube.com/shorts/FW9pdy6a3WY",
    howTo: {
      setup: "Lie on your back, heels on sliders, knees bent, hips lifted.",
      steps: ["Keep the hips high and bridge held.", "Slide the heels away until the legs are nearly straight.", "Pull the heels back in with the hamstrings."],
      mistakes: ["Letting the hips drop as the legs extend", "Pushing through the toes instead of the heels"],
      easier: "Smaller range; one leg lightly assisting.",
      harder: "Slow the extension; pause at full reach.",
    },
  },
  {
    id: "kb-gorilla-rows",
    name: "KB Gorilla Rows",
    emoji: "🦍",
    type: "strength",
    setType: "reps-perside",
    loaded: true,
    equipment: ["dumbbell", "full"],
    cue: "Squeeze shoulder blades, brace, belly button to spine.",
    videoUrl: "https://youtu.be/UsxcaALqr2c?si=TTMhrSQdM6UhiB4V",
    howTo: {
      setup: "Two kettlebells on the floor between the feet, hinge to a flat-back stance.",
      steps: ["Grip both bells, hips back, back flat.", "Row one bell to the hip while the other supports.", "Lower and row the other side, staying square."],
      mistakes: ["Rotating the torso to yank the weight", "Rounding the back on the hinge"],
      easier: "Lighter bells; row one side at a time.",
      harder: "Add load or a pause at the top of each row.",
    },
  },
  {
    id: "oblique-crunches",
    name: "Oblique Crunches",
    emoji: "🌀",
    type: "strength",
    setType: "reps-perside",
    loaded: false,
    equipment: ["bodyweight"],
    cue: "Use your breath to engage the core.",
    videoUrl: "https://youtu.be/QxaKQG-gmPY?si=FC9o-U7uG4offNVA",
    howTo: {
      setup: "Lie on your back, hands by the head, knees bent.",
      steps: ["Crunch up and rotate one elbow toward the opposite knee.", "Exhale and engage the obliques at the top.", "Lower with control; complete the side, then switch."],
      mistakes: ["Yanking on the neck", "Using momentum instead of the obliques"],
      easier: "Reduce the range; feet flat and stable.",
      harder: "Slow the tempo and pause at the top of each rep.",
    },
  },

  // ============================ DAY 4 — bodyweight circuit (Opt 4) ============================
  {
    id: "burpees",
    name: "Burpees",
    emoji: "💥",
    type: "cardio",
    setType: "reps",
    loaded: false,
    equipment: ["bodyweight"],
    cue: "Smooth and steady — full extension at the top.",
    howTo: {
      setup: "Stand in a clear space.",
      steps: ["Drop the hands down and kick the feet back to a plank.", "Lower the chest (optional), then jump the feet back in.", "Stand and jump with the hands overhead."],
      mistakes: ["Letting the hips sag in the plank", "Skipping full extension at the top"],
      easier: "Step the feet back and skip the jump.",
      harder: "Add a push-up at the bottom of each rep.",
    },
  },
  {
    id: "mountain-climbers",
    name: "Mountain Climbers",
    emoji: "⛰️",
    type: "cardio",
    setType: "timed",
    loaded: false,
    equipment: ["bodyweight"],
    cue: "Keep the hips level, quick feet.",
    howTo: {
      setup: "Start in a high plank, shoulders over wrists.",
      steps: ["Drive one knee toward the chest.", "Switch quickly, driving the other knee in.", "Keep a steady, controlled pace."],
      mistakes: ["Piking the hips up", "Bouncing too high"],
      easier: "Slow the tempo.",
      harder: "Pick up the cadence while keeping form."},
  },
  {
    id: "push-ups",
    name: "Push-ups",
    emoji: "💪",
    type: "strength",
    setType: "reps",
    loaded: false,
    equipment: ["bodyweight"],
    cue: "Body in one line, elbows about 45°.",
    howTo: {
      setup: "High plank, hands a little wider than the shoulders.",
      steps: ["Lower the chest toward the floor, elbows back at ~45°.", "Keep the body in a straight line.", "Press back to the top."],
      mistakes: ["Letting the hips sag or pike", "Flaring the elbows to 90°"],
      easier: "Drop to the knees or elevate the hands.",
      harder: "Slow the lowering or elevate the feet.",
    },
  },
  {
    id: "plank-hold",
    name: "Plank Hold",
    emoji: "📏",
    type: "strength",
    setType: "timed",
    loaded: false,
    equipment: ["bodyweight"],
    // NOTE: source cell for the duration was garbled ("ustin"). Defaulted to
    // 30 sec in program.ts — a one-line change once the coach confirms.
    cue: "Squeeze everything — glutes, quads, core — one straight line.",
    howTo: {
      setup: "Forearms under the shoulders, feet hip-width.",
      steps: ["Hold a straight line from head to heels.", "Brace the core and squeeze the glutes.", "Breathe steadily for the hold."],
      mistakes: ["Letting the hips sag or pike up", "Holding the breath"],
      easier: "Drop to the knees.",
      harder: "Lift one foot, or add a gentle reach."},
  },

  // ============================ DAY 4 — conditioning choices (free/timed) ============================
  {
    id: "swim",
    name: "Swim",
    emoji: "🏊",
    type: "cardio",
    setType: "free",
    loaded: false,
    equipment: ["full"],
    cue: "Intervals between sprints and easy laps.",
    howTo: {
      setup: "Pool, goggles, a rough plan for sprint vs easy laps.",
      steps: ["Warm up with a few easy laps.", "Alternate a hard sprint lap with an easy recovery lap.", "Cool down easy for the last few laps."],
      mistakes: ["Going all-out with no recovery laps", "Skipping the warm-up"],
      easier: "Longer easy intervals between sprints.",
      harder: "Shorten the recovery laps.",
    },
  },
  {
    id: "mountain-biking",
    name: "Mountain Biking",
    emoji: "🚵",
    type: "cardio",
    setType: "free",
    loaded: false,
    equipment: ["full"],
    cue: "Get out and ride — mix the terrain.",
    howTo: {
      setup: "Bike, helmet, a trail or route in mind.",
      steps: ["Warm up on easy terrain.", "Mix climbs and flats; push the climbs.", "Stay loose on the descents."],
      mistakes: ["Skipping the warm-up", "Death-gripping the bars"],
      easier: "Flatter route, shorter ride.",
      harder: "More climbing or a longer loop.",
    },
  },
  {
    id: "treadmill-incline-vest",
    name: "Incline Treadmill Walk + Weighted Vest",
    emoji: "🥾",
    type: "cardio",
    setType: "timed",
    loaded: false,
    equipment: ["full"],
    cue: "30 min steady — tall posture, let the incline do the work.",
    howTo: {
      setup: "Weighted vest on, treadmill set to a challenging incline.",
      steps: ["Walk tall, no hanging on the rails.", "Hold a brisk, steady pace.", "Keep it up for the full 30 minutes."],
      mistakes: ["Leaning on the handrails", "Setting the incline so high your form breaks"],
      easier: "Lower the incline or drop the vest.",
      harder: "Raise the incline or add vest weight.",
    },
  },

  // ============================ SHARED COOL-DOWN ============================
  {
    id: "cooldown-walk",
    name: "Slow Walk / Bike",
    emoji: "🚶",
    type: "cooldown",
    setType: "timed",
    loaded: false,
    equipment: ["bodyweight"],
    cue: "5–10 min easy — let the heart rate come down.",
    howTo: {
      setup: "Treadmill, bike, or just a loop around the room.",
      steps: ["Keep it easy and conversational.", "Let the breathing settle.", "Loosen up as you go."],
      mistakes: ["Skipping it entirely", "Keeping the intensity high"],
      easier: "Shorten to 5 minutes.",
      harder: "Extend to 10 minutes of easy movement.",
    },
  },
  {
    id: "stretch",
    name: "Stretch",
    emoji: "🤸",
    type: "cooldown",
    setType: "free",
    loaded: false,
    equipment: ["bodyweight"],
    cue: "Hit whatever feels tight from today — no rush.",
    howTo: {
      setup: "A bit of floor space.",
      steps: ["Target the muscles you just worked.", "Ease into each stretch, breathe.", "Hold each for 20–30 seconds."],
      mistakes: ["Bouncing into a stretch", "Forcing painful range"],
      easier: "Fewer, gentler stretches.",
      harder: "Hold longer and add a few extra positions.",
    },
  },
];

const BY_ID = new Map(EXERCISES.map((e) => [e.id, e]));

export function getExercise(id: string): Exercise | undefined {
  return BY_ID.get(id);
}
